---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 8.0 
summary: 'Se si esegue ONTAP Select su VMware ESXi, è possibile aggiornare il software ESXi da una versione precedente supportata a ESXi 8.0 o successiva. Prima di effettuare l"aggiornamento, è necessario comprendere il processo e selezionare la procedura di aggiornamento appropriata.' 
---
= Aggiorna a VMware ESXi 8.0 o versione successiva per ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si esegue ONTAP Select su VMware ESXi, è possibile aggiornare il software ESXi da una versione precedente supportata a ESXi 8.0 o successiva. Prima di effettuare l'aggiornamento, è necessario comprendere il processo e selezionare la procedura di aggiornamento appropriata.



== Preparati all'aggiornamento di VMware ESXi

Preparare e selezionare la procedura di aggiornamento più adatta al proprio ambiente prima di aggiornare il software ESXi sugli hypervisor che ospitano un cluster ONTAP Select .

.Fasi
. *Impara a conoscere come aggiornare VMware ESXi*
+
L'aggiornamento del software ESXi è un processo descritto e supportato da VMware. Il processo di aggiornamento dell'hypervisor fa parte della procedura di aggiornamento più estesa quando si utilizza ONTAP Select. Per ulteriori informazioni, consultare la documentazione VMware.

. *Seleziona una procedura di aggiornamento*
+
Sono disponibili diverse procedure di aggiornamento. Selezionare la procedura appropriata in base ai seguenti criteri:

+
** ONTAP Select la dimensione del cluster
+
Sono supportati sia cluster a nodo singolo che cluster a più nodi.

** Utilizzo di ONTAP Select Deploy
+
L'aggiornamento è possibile sia con che senza l'utilità Deploy.

+

TIP: Selezionare una procedura di aggiornamento che utilizzi l'utility di amministrazione di deploy.

+
Eseguire un aggiornamento ESXi tramite l'utility di amministrazione Deploy è l'opzione più generale e resiliente. Tuttavia, potrebbero verificarsi casi in cui Deploy non è disponibile o non può essere utilizzato. Ad esempio, l'aggiornamento a ESXi 8.0 non è supportato con le versioni precedenti di ONTAP Select e dell'utility di amministrazione Deploy.

+
Se si utilizzano queste versioni precedenti e si tenta di eseguire un aggiornamento, è possibile lasciare la macchina virtuale ONTAP Select in uno stato in cui non è possibile avviarla. In questo caso, è necessario selezionare una procedura di aggiornamento che non utilizza la distribuzione. Fare riferimento a. link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] per ulteriori informazioni.



. *Aggiornare l'utilità di amministrazione Deploy*
+
Prima di eseguire una procedura di aggiornamento tramite l'utilità Deploy, potrebbe essere necessario aggiornare l'istanza di Deploy. In generale, è consigliabile aggiornare alla versione più recente di Deploy. L'utility Deploy deve supportare la versione di ONTAP Select in uso.  Fare riferimento allink:reference_release_notes.html["Note sulla versione ONTAP Select"] per maggiori informazioni.

. *Dopo il completamento della procedura di aggiornamento*
+
Se si seleziona una procedura di aggiornamento che utilizza l'utility di distribuzione, è necessario eseguire un'operazione di refresh del cluster utilizzando Deploy dopo che tutti i nodi sono stati aggiornati. Per ulteriori informazioni, vedere aggiornamento della configurazione del cluster di implementazione.





== Aggiorna un cluster a nodo singolo utilizzando l'implementazione

È possibile utilizzare l'utility di amministrazione di deploy come parte della procedura per aggiornare l'hypervisor VMware ESXi che ospita un cluster a nodo singolo ONTAP Select.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore.
. Sposta il nodo nello stato offline:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Aggiornare l'host hypervisor su cui è in esecuzione ONTAP Select a ESXi 8.0 o versione successiva utilizzando la procedura fornita da VMware.
. Sposta il nodo nello stato online:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Una volta attivato il nodo, verificare che il cluster funzioni correttamente.
+
Esempio:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Al termine
È necessario eseguire un'operazione di refresh del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster multi-nodo utilizzando l'implementazione

È possibile utilizzare l'utility di amministrazione di Deploy come parte della procedura per aggiornare gli hypervisor VMware ESXi che ospitano un cluster multi-nodo ONTAP Select.

.A proposito di questa attività
È necessario eseguire questa procedura di aggiornamento per ciascuno dei nodi del cluster, un nodo alla volta. Se il cluster contiene quattro o più nodi, è necessario aggiornare i nodi di ciascuna coppia ha in sequenza prima di passare alla coppia ha successiva.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore.
. Sposta il nodo nello stato offline:
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. Aggiornare l'host hypervisor su cui è in esecuzione ONTAP Select a ESXi 8.0 o versione successiva utilizzando la procedura fornita da VMware.
+
Per ulteriori informazioni, consultare la sezione preparazione all'aggiornamento di VMware ESXi.

. Sposta il nodo nello stato online:
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. Una volta attivato il nodo, verificare che il failover dello storage sia attivato e che il cluster funzioni correttamente.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Al termine
È necessario eseguire la procedura di aggiornamento per ciascun host utilizzato nel cluster ONTAP Select. Una volta aggiornati tutti gli host ESXi, è necessario eseguire un'operazione di aggiornamento del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster a nodo singolo senza eseguire l'implementazione

È possibile aggiornare l'hypervisor VMware ESXi che ospita un cluster a nodo singolo ONTAP Select senza utilizzare l'utility di amministrazione Deploy.

.Fasi
. Accedere all'interfaccia della riga di comando di ONTAP e arrestare il nodo.
. Utilizzando VMware vSphere, verificare che la macchina virtuale ONTAP Select sia spenta.
. Aggiornare l'host hypervisor su cui è in esecuzione ONTAP Select a ESXi 8.0 o versione successiva utilizzando la procedura fornita da VMware.
+
Per ulteriori informazioni, consultare la sezione preparazione all'aggiornamento di VMware ESXi.

. Utilizzando VMware vSphere, accedere a vCenter ed effettuare le seguenti operazioni:
+
.. Aggiungere un disco floppy alla macchina virtuale ONTAP Select.
.. Accendere la macchina virtuale ONTAP Select.
.. Accedere all'interfaccia utente di ONTAP utilizzando SSH con l'account amministratore.


. Una volta attivato il nodo, verificare che il cluster funzioni correttamente.
+
Esempio:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.Al termine
È necessario eseguire un'operazione di refresh del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster multi-nodo senza eseguire l'implementazione

È possibile aggiornare gli hypervisor VMware ESXi che ospitano un cluster multi-nodo ONTAP Select senza utilizzare l'utility di amministrazione Deploy.

.A proposito di questa attività
È necessario eseguire questa procedura di aggiornamento per ciascuno dei nodi del cluster, un nodo alla volta. Se il cluster contiene quattro o più nodi, è necessario aggiornare i nodi di ciascuna coppia ha in sequenza prima di passare alla coppia ha successiva.

.Fasi
. Accedere all'interfaccia della riga di comando di ONTAP e arrestare il nodo.
. Utilizzando VMware vSphere, verificare che la macchina virtuale ONTAP Select sia spenta.
. Aggiornare l'host hypervisor su cui è in esecuzione ONTAP Select a ESXi 8.0 o versione successiva utilizzando la procedura fornita da VMware.
. Utilizzando VMware vSphere, accedere a vCenter ed effettuare le seguenti operazioni:
+
.. Aggiungere un disco floppy alla macchina virtuale ONTAP Select.
.. Accendere la macchina virtuale ONTAP Select.
.. Accedere all'interfaccia utente di ONTAP utilizzando SSH con l'account amministratore.


. Una volta attivato il nodo, verificare che il failover dello storage sia attivato e che il cluster funzioni correttamente.
+
.Mostra esempio
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.Al termine
È necessario eseguire la procedura di aggiornamento per ciascun host utilizzato nel cluster ONTAP Select.
