---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: Prima di installare e gestire il plug-in Deploy vCenter, è necessario eseguire diverse operazioni. 
---
= Prima di iniziare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di installare e gestire il plug-in Deploy vCenter, è necessario eseguire diverse operazioni.



== Decidere se utilizzare l'interfaccia utente Web di implementazione o la CLI

Nella maggior parte dei casi, l'interfaccia utente Web di implementazione offre l'opzione più comoda per la gestione del plug-in vCenter, opzione descritta in questa guida. Tuttavia, è anche possibile gestire il plug-in utilizzando l'interfaccia della riga di comando di deploy. Per ulteriori informazioni, digitare i seguenti comandi al prompt di deploy CLI:

* `deploy plugin ?` (I sottocomandi includono: Installazione, rimozione, visualizzazione e aggiornamento)
* `deploy plugin-packages show`




== Preparazione comune a tutte le attività di gestione

Esistono diversi passaggi da eseguire indipendentemente dall'attività di gestione. La preparazione comune comprende:

* Leggere la sezione Guida introduttiva per acquisire familiarità con il plug-in Deploy vCenter.
* Assicurarsi che l'utilità di amministrazione di ONTAP Select Deploy sia installata e in esecuzione. Per ulteriori informazioni, consultare la Guida all'installazione e alla distribuzione dei cluster di VMware.
* Acquisizione delle credenziali dell'account:
+
** Implementare l'account amministratore
** Account server vCenter


* Assicurarsi che l'utility di implementazione disponga dell'accesso di rete alla porta 443 del server vCenter.


A seconda dell'attività di gestione, potrebbe essere necessaria una preparazione aggiuntiva.



== Preparazione degli account server vCenter

Prima di installare e utilizzare il plug-in di distribuzione, è necessario creare gli account vCenter con i privilegi richiesti. È possibile creare un singolo account con tutti i privilegi necessari o creare più account ciascuno con un singolo privilegio. Per semplicità, l'esempio seguente distribuisce i privilegi vCenter in tre ruoli separati che possono essere assegnati ai tre account corrispondenti.



=== Convalida dell'accesso dell'utente finale al plug-in

È necessario un account per convalidare l'accesso al plug-in tramite vSphere. L'account deve disporre del seguente privilegio vCenter: sessions.validate.session. Una volta creato l'account in vCenter, è necessario definirlo nell'utility di amministrazione di distribuzione. Nell'interfaccia utente Web Deploy, fare clic sulla scheda Administration (Amministrazione), quindi su Credentials (credenziali) per specificare la posizione e le credenziali del server vCenter.

Questo account viene utilizzato nei seguenti modi:

* Il server vCenter denominato diventa disponibile come destinazione di installazione nella finestra di dialogo di registrazione del plug-in.
* L'account viene utilizzato da Deploy per convalidare le richieste degli utenti vSphere di accedere al plug-in dopo l'installazione del plug-in.




=== Gestione del plug-in

Nell'interfaccia utente Web di implementazione, è possibile installare il plug-in e quindi aggiornarlo o rimuoverlo. Ogni volta che si esegue una di queste azioni di gestione, viene richiesto un account vCenter nella finestra popup. Ciascuna delle azioni di gestione viene controllata tramite un privilegio vCenter separato.

Per installare, aggiornare e rimuovere il plug-in, è necessario assegnare i seguenti privilegi:

* Interno
+
** Registrare l'interno
** Aggiornare l'estensione
** Annullare la registrazione dell'interno




È possibile creare un singolo ruolo e un account con tutti e tre i privilegi o dividere i privilegi tra più account in base alle esigenze.



=== Accesso al plug-in

Gli utenti finali possono accedere al plug-in tramite vSphere. È necessario assegnare il seguente privilegio agli account che utilizzeranno il plug-in:

* NetApp
+
** Implementazione di ONTAP Select
+
*** Amministratore





