---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 'Dopo aver implementato un cluster ONTAP Select, è possibile aggiornare l"immagine ONTAP di ciascun nodo secondo necessità utilizzando la procedura di aggiornamento software standard di ONTAP.' 
---
= Aggiornare i nodi ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver implementato un cluster ONTAP Select, è possibile aggiornare l'immagine ONTAP in ciascun nodo del cluster in base alle necessità.


CAUTION: Non è possibile utilizzare l'utility di amministrazione di Deploy per eseguire gli aggiornamenti dei nodi ONTAP Select esistenti. L'utility di implementazione può essere utilizzata solo per creare nuovi cluster ONTAP Select.



== Procedura generale

Per aggiornare un nodo ONTAP Select esistente, attenersi alla procedura descritta di seguito.

.Fasi
. Accedi alla link:https://mysupport.netapp.com/site/downloads/["Download dal sito di supporto NetApp"^] page.
. Scorri verso il basso e seleziona *ONTAP Select Image*.
. Seleziona la versione desiderata dell'immagine di installazione.
. Leggere il Contratto di licenza con l'utente finale (EULA) e selezionare *Accetta e continua*.
. Seleziona e scarica il pacchetto *ONTAP Select Image Upgrade* appropriato. Rispondi a tutte le richieste secondo necessità.
+
Esaminare la link:reference_release_notes.html["note di rilascio"] per ulteriori informazioni e per eventuali procedure richieste prima di aggiornare un nodo ONTAP Select.

. Aggiorna il nodo ONTAP Select utilizzando le procedure standard di aggiornamento ONTAP con il file di aggiornamento ONTAP Select. Per informazioni sui percorsi di aggiornamento supportati, fare riferimento al link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Percorsi di aggiornamento ONTAP supportati"^].




== Ripristinare un nodo ONTAP Select

Non è possibile ripristinare un nodo ONTAP Select a una versione precedente a quella su cui è stato installato originariamente. Ad esempio:

ONTAP Select 9.16.1 è inizialmente installato:: È possibile aggiornare il nodo alla versione 9.17.1 e poi tornare alla versione 9.16.1, se necessario.
ONTAP Select 9.17.1 è inizialmente installato:: Non è possibile ripristinare la versione precedente perché non è stata installata alcuna versione precedente.




== Utilizzare il driver di rete VMXNET3

VMXNET3 è il driver di rete predefinito incluso nelle nuove implementazioni del cluster su VMware ESXi. Se si aggiorna un nodo ONTAP Select esistente che esegue ONTAP Select 9,4 o versione precedente, il driver di rete non viene aggiornato automaticamente. È necessario eseguire l'aggiornamento manuale a VMXNET3. Contattare il supporto NetApp per assistenza con l'aggiornamento.

.Informazioni correlate
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Panoramica sull'aggiornamento di ONTAP"^]
