---
sidebar: sidebar 
permalink: concept_cli_before.html 
keywords: administer, administering, cli, before you begin 
summary: 'È possibile accedere alla shell di gestione della distribuzione utilizzando SSH. Dopo aver effettuato l"accesso, è possibile eseguire diverse procedure amministrative.' 
---
= Prima di iniziare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile accedere alla shell di gestione della distribuzione utilizzando SSH. Dopo aver effettuato l'accesso, è possibile eseguire diverse procedure amministrative.

In generale, le procedure che è possibile eseguire utilizzando la CLI rientrano in una delle tre categorie.

Implementare un cluster ONTAP Select:: È possibile implementare un cluster a nodo singolo o a più nodi.
Eseguire una procedura con un cluster ONTAP Select esistente:: Le procedure amministrative sono organizzate in varie categorie, ad esempio _Security_ e _Clusters_.
Eseguire una procedura sull'utilità di implementazione:: Esistono diverse procedure specifiche per la distribuzione (ad esempio, la modifica della password dell'amministratore).

