---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Con il modello di licenza Capacity Tiers, il numero di serie del nodo a nove cifre è lo stesso del numero di serie della licenza assegnato al nodo. Tuttavia, i numeri di serie assegnati ai nodi che utilizzano il modello di licenza Pool di capacità hanno un formato diverso. 
---
= Numeri di serie dei nodi per il modello di licenza di pool di capacità ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con il modello di licenza Capacity Tiers, il numero di serie del nodo a nove cifre è lo stesso del numero di serie della licenza assegnato al nodo. Tuttavia, i numeri di serie assegnati ai nodi che utilizzano il modello di licenza Pool di capacità hanno un formato diverso.

Il numero di serie di un nodo che utilizza la licenza Capacity Pools ha il seguente formato:

`999 ppppppppp nnnnnnnn`


NOTE: Gli spazi sono stati aggiunti per maggiore chiarezza, ma non fanno parte del numero di serie effettivo.

La tabella seguente descrive ogni sezione del numero di serie del nodo da sinistra a destra.

[cols="15,85"]
|===
| Sezione | Descrizione 


| "999" | Valore costante di tre cifre riservato da NetApp. 


| ppppppppppp | Numero di serie della licenza a nove cifre variabile assegnato al pool di capacità da NetApp 


| nnnnnnnn | Valore variabile a otto cifre generato dal Manager di licenza per ciascun nodo che utilizza il pool di capacità 
|===

CAUTION: Quando si apre un caso con NetApp support relativo a un nodo che utilizza una licenza Capacity Pool, è necessario fornire il numero di serie della licenza Capacity Pool a nove cifre. Non è possibile fornire il numero di serie completo del nodo a venti cifre. È possibile ricavare il numero di serie della licenza dal numero di serie del nodo saltando le prime tre cifre del numero di serie del nodo ('999') ed estraendo le nove cifre successive (ppppppppp).
