---
sidebar: sidebar 
permalink: concept_vpi_vcenter_integration.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration 
summary: 'Il plug-in di implementazione è strettamente integrato con il server vCenter. Grazie a questa integrazione, è possibile navigare facilmente tra le risorse gestite dall"utility di implementazione e dal server vCenter. Di seguito sono riportati alcuni esempi di questa integrazione.' 
---
= Implementare plug-in e integrazione vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il plug-in di implementazione è strettamente integrato con il server vCenter. Grazie a questa integrazione, è possibile navigare facilmente tra le risorse gestite dall'utility di implementazione e dal server vCenter. Di seguito sono riportati alcuni esempi di questa integrazione.



== Risorse VMware assegnate a un cluster ONTAP Select

Un cluster ONTAP Select viene eseguito su VMware come un insieme di uno o più nodi. Ciascun nodo è una macchina virtuale dedicata su un host ESXi diverso. Un cluster ONTAP Select è associato alle seguenti risorse VMware:

* Host
* Macchine virtuali ONTAP
* Datastore
* Reti


Esistono diversi modi per visualizzare le risorse VMware utilizzate da uno specifico cluster ONTAP Select.



== Visualizzare le risorse VMware per un cluster tramite il plug-in

È possibile visualizzare le risorse VMware assegnate a un cluster ONTAP Select attraverso il plug-in di implementazione.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Fare clic su *ONTAP Select Clusters* nel riquadro *elenchi di inventario globali*.
. Fare clic sul cluster desiderato nell'elenco a destra.
. Fare clic sulla scheda *altri oggetti* e selezionare la categoria di risorse desiderata nella parte superiore della pagina.
. Selezionare una risorsa VMware specifica per visualizzare ulteriori informazioni.




== Visualizza i cluster ONTAP Select attraverso una macchina virtuale ESXi

È possibile visualizzare il cluster ONTAP Select e le risorse del cluster associate accedendo a una macchina virtuale VMware.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Fare clic su *Menu* nella parte superiore, quindi su *VM e modelli*.
. Selezionare la macchina virtuale desiderata nell'elenco a sinistra.
. Fare clic sulla scheda *altri oggetti* per visualizzare il cluster ONTAP Select in esecuzione nella macchina virtuale.
. Per visualizzare l'intera raccolta di risorse VMware associate al cluster, fare clic sul cluster ONTAP Select, quindi sulla scheda *altri oggetti*.




== Creare un cluster a nodo singolo su un host ESXI

È possibile selezionare un host hypervisor ESXI tramite l'interfaccia vSphere e implementare un cluster a nodo singolo ONTAP Select.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Fare clic su *Menu* nella parte superiore, quindi su *host e cluster*.
. Fare clic con il pulsante destro del mouse sull'host dell'hypervisor desiderato a sinistra, selezionare *ONTAP Select*, quindi fare clic su *New ONTAP Select* (nuovo hypervisor).
. Completare il processo di implementazione seguendo i passaggi descritti in link:task_deploy_cluster.html["Implementare un cluster ONTAP Select"].

