---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: 'Quando si inizia a esplorare ONTAP Select e si pianifica un"implementazione, è utile acquisire familiarità con la terminologia e i concetti chiave.' 
---
= Terminologia e concetti chiave
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si inizia a esplorare ONTAP Select e si pianifica un'implementazione, è utile acquisire familiarità con la terminologia e i concetti chiave.

Implementazione di ONTAP Select:: ONTAP Select Deploy è l'utility di amministrazione utilizzata per implementare i cluster ONTAP Select. L'utility di implementazione viene eseguita in una macchina virtuale Linux dedicata. È possibile accedere all'utility di implementazione tramite l'interfaccia utente Web, la shell di gestione CLI e l'API REST.
Host hypervisor rispetto al nodo ONTAP Select:: Un _host hypervisor_ è la piattaforma hardware principale che ospita una macchina virtuale ONTAP Select. Quando una macchina virtuale ONTAP Select viene implementata e attiva su un host hypervisor, viene considerata un _nodo ONTAP Select_.
Cluster ONTAP Select:: È possibile creare un _cluster ONTAP Select_ composto da uno, due, quattro, sei o otto nodi. I cluster multi-nodo contengono sempre una o più coppie ha. Ad esempio, un cluster a quattro nodi è costituito da due coppie ha. Un cluster a nodo singolo non fornisce funzionalità ha.
Preparazione dell'ambiente host dell'hypervisor:: Prima di utilizzare l'utility di amministrazione Deploy per implementare un cluster ONTAP Select, è necessario preparare gli host hypervisor in cui verrà eseguito ONTAP Select, inclusi gli ambienti di storage e di rete. Questa preconfigurazione dell'host viene eseguita al di fuori del prodotto ONTAP Select in base ai requisiti e alle limitazioni correnti.
Valutazione rispetto alle implementazioni in produzione:: Ogni nodo ONTAP Select viene eseguito con una _licenza di valutazione_ o con una _licenza acquistata_. Una licenza di valutazione consente di valutare ONTAP Select prima di implementarlo in un ambiente di produzione. La licenza di valutazione viene generata e applicata automaticamente. Se si implementa un cluster in un ambiente di produzione, è necessario acquistare una licenza che prevede la scelta di:
+
--
* Modello di licensing
* Capacità dello storage
* Offerta di licenze per la piattaforma


--
Modello di licensing dei Tier di capacità:: Il modello di licensing dei Tier di capacità è l'opzione originale quando si concederà in licenza lo storage per un'implementazione ONTAP Select. Si basa sul modello ONTAP utilizzato con NetApp AFF e FAS. Per ciascun nodo è necessaria una licenza separata. La capacità dello storage è bloccata sul nodo e perpetua (non è richiesto alcun rinnovo).
Modello di licensing dei pool di capacità:: Il modello di licensing dei pool di capacità è stato introdotto con ONTAP Select 9.5 utilizzando Deploy 2.10. Per ogni pool di capacità di storage è necessaria una licenza separata. La licenza del pool di capacità è bloccata in un'istanza del Manager di licenza (ovvero un'istanza di implementazione) e deve essere rinnovata in base ai termini dell'acquisto. È possibile concedere in licenza e utilizzare un numero qualsiasi di pool di capacità all'interno dell'organizzazione. Tuttavia, poiché i pool di capacità sono condivisi dai nodi ONTAP Select, in genere sono necessarie meno licenze rispetto ai livelli di capacità delle licenze.
Manager di licenza:: Il Manager di licenza è un componente software che supporta le licenze dei pool di capacità. Attualmente fa parte dell'utilità di amministrazione di Deploy. LM affitta lo storage ai nodi ONTAP Select dai pool condivisi gestiti. L' _ID blocco licenza_ è una stringa numerica che identifica in modo univoco ogni istanza LM e quindi ogni istanza di implementazione. Per generare un file di licenza, è necessario utilizzare sia il numero di serie della licenza di Capacity Pool che l'LID.
Offerte di licenze per la piattaforma:: Sono disponibili tre offerte di licenza che determinano le capacità delle dimensioni della macchina virtuale ONTAP Select al momento dell'acquisto di una licenza:
+
--
* Standard
* Premium
* Premium XL


--


Per ulteriori informazioni, vedere le due sezioni _Plan_ e _License_.

Pool di storage e datastore:: Un _pool di storage_ di ONTAP Select è un contenitore logico di dati progettato per astrarre e nascondere lo storage fisico sottostante. Un pool di storage è indipendente dall'hypervisor. Se implementato su un host hypervisor ESXi, il pool di storage ONTAP Select è sinonimo di _datastore_ VMware.
MTU del cluster:: La MTU del cluster è una funzione che consente di configurare le dimensioni della MTU utilizzata sulla rete interna utilizzata con un cluster a più nodi ONTAP Select. L'utility di amministrazione di Deploy regola le dimensioni MTU durante la configurazione delle coppie ha per adattarsi all'ambiente di rete. È anche possibile impostare manualmente il valore.
ONTAP Select vNAS:: La soluzione vNAS di ONTAP Select consente a un nodo ONTAP Select di accedere agli archivi dati VMware sullo storage esterno. Con ONTAP Select vNAS, non è più necessario un controller RAID locale; si presuppone che la funzionalità RAID sia fornita dallo storage remoto. ONTAP Select vNAS può essere configurato nei seguenti modi:
+
--
* VMware vSAN
* Storage array esterno generico


--


In entrambi i casi, lo storage esterno deve essere configurato prima di creare un cluster ONTAP Select o espandere la capacità di storage di un nodo esistente.

Re-hosting del nodo:: Quando si implementa un cluster che utilizza lo storage esterno disponibile tramite la soluzione vNAS di ONTAP Select (VMware vSAN o un array di storage esterno generico), la macchina virtuale ESXi che ospita il nodo ONTAP Select può essere spostata attraverso le azioni utilizzando le seguenti funzionalità VMware:
+
--
* VMotion
* Alta disponibilità (ha)
* DRS (Distributed Resource Scheduler)
+
L'utility di implementazione di ONTAP Select rileva lo spostamento della macchina virtuale durante l'esecuzione di un'operazione sul cluster, ad esempio:

* cluster online
* cluster offline
* aggiunta di storage
+
Quando si sposta una macchina virtuale, l'utility di implementazione aggiorna il database interno e configura il nuovo host ESXi. Tutte le azioni eseguite sul nodo ONTAP Select vengono bloccate fino al completamento dello spostamento della macchina virtuale e della distribuzione degli aggiornamenti.



--
Servizio mediatore:: L'utility ONTAP Select Deploy include un servizio di mediazione che si connette ai nodi nei cluster a due nodi attivi. Questo servizio monitora ogni coppia ha e assiste nella gestione dei guasti.



CAUTION: Se si dispone di uno o più cluster a due nodi attivi, la macchina virtuale ONTAP Select Deploy che amministra i cluster deve essere sempre in esecuzione. Se la macchina virtuale di implementazione viene arrestata, il servizio mediatore non è disponibile e la funzionalità ha viene persa per i cluster a due nodi.

Scheda di sicurezza MetroCluster:: SDS di MetroCluster è una funzionalità che fornisce un'opzione di configurazione aggiuntiva quando si implementa un cluster ONTAP Select a due nodi. A differenza di una tipica implementazione ROBO a due nodi, i nodi SDS MetroCluster possono essere separati da una distanza molto maggiore. Questa separazione fisica consente ulteriori casi di utilizzo, come il disaster recovery. È necessario disporre di una licenza Premium o superiore per utilizzare MetroCluster SDS. Inoltre, la rete tra i nodi deve supportare un requisito minimo di latenza.
Archivio di credenziali:: L'archivio delle credenziali di implementazione è un database sicuro che contiene le credenziali dell'account. Viene utilizzato principalmente per registrare gli host hypervisor durante la creazione di un nuovo cluster. Per ulteriori informazioni, consulta la sezione _Plan_.
Efficienza dello storage:: ONTAP Select offre opzioni di efficienza dello storage simili alle opzioni di efficienza dello storage presenti negli array FAS e AFF. Concettualmente, ONTAP Select con SSD DAS (Direct-Attached Storage) (che utilizzano una licenza Premium) è simile a un array AFF. Le configurazioni che utilizzano DAS con HDD e tutte le configurazioni vNAS devono essere considerate simili a quelle di un array FAS. La differenza principale tra le due configurazioni è che ONTAP Select con SSD DAS supporta la deduplica a livello di aggregato inline e la deduplica in background a livello di aggregato. Le restanti opzioni di efficienza dello storage sono disponibili per entrambe le configurazioni.
+
--
Le configurazioni predefinite di vNAS consentono una funzione di ottimizzazione della scrittura nota come SIDL (Single instance data logging). Con ONTAP Select 9.6 e versioni successive, le funzionalità di efficienza dello storage ONTAP in background sono qualificate con SIDL abilitato. Per ulteriori informazioni, consulta la sezione _deep dive_.

--
Refresh del cluster:: Dopo aver creato un cluster, è possibile apportare modifiche alla configurazione del cluster o della macchina virtuale al di fuori dell'utilità di implementazione utilizzando ONTAP o gli strumenti di amministrazione dell'hypervisor. È inoltre possibile migrare una macchina virtuale che causa modifiche alla configurazione. Quando si verificano queste modifiche, l'utilità di implementazione non viene aggiornata automaticamente e può non essere sincronizzata con lo stato del cluster. È possibile utilizzare la funzione di aggiornamento del cluster per aggiornare il database di configurazione di implementazione. Il refresh del cluster è disponibile tramite l'interfaccia utente Web di implementazione, la shell di gestione CLI e l'API REST.
RAID software:: Quando si utilizza lo storage DAS (Direct-Attached Storage), la funzionalità RAID viene tradizionalmente fornita tramite un controller RAID hardware locale. È invece possibile configurare un nodo per l'utilizzo di _RAID software_, in cui il nodo ONTAP Select fornisce la funzionalità RAID. Se si utilizza RAID software, non è più necessario un controller RAID hardware.
Installazione dell'immagine ONTAP Select:: A partire da ONTAP Select Deploy 2.8, l'utility di amministrazione di deploy contiene solo una singola versione di ONTAP Select. La versione inclusa è la più recente disponibile al momento del rilascio. La funzionalità di installazione dell'immagine ONTAP Select consente di aggiungere versioni precedenti di ONTAP Select all'istanza dell'utilità di distribuzione, che può essere utilizzata durante la distribuzione di un cluster ONTAP Select. Vedere link:task_cli_deploy_image_add.html["Aggiungi immagini ONTAP Select per ulteriori informazioni"].



NOTE: È necessario aggiungere un'immagine ONTAP Select con una versione precedente alla versione originale inclusa nell'istanza di distribuzione. L'aggiunta di versioni successive di ONTAP Select senza aggiornare anche la distribuzione non è supportata.

Amministrazione di un cluster ONTAP Select dopo la distribuzione:: Dopo aver implementato un cluster ONTAP Select, è possibile configurarlo come se fosse un cluster ONTAP basato su hardware. Ad esempio, è possibile configurare un cluster ONTAP Select utilizzando Gestione di sistema o l'interfaccia della riga di comando standard di ONTAP.


.Informazioni correlate
link:task_cli_deploy_image_add.html["Aggiungere un'immagine ONTAP Select da distribuire"]
