---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Il modello di licenza Capacity Pool è diverso dal modello di Tier di capacità. Invece di dedicare capacità di storage a ciascun nodo, la capacità di storage viene allocata a un pool e condivisa tra più nodi. Sono stati creati ulteriori componenti e processi per supportare il modello dei pool di capacità. 
---
= Dettagli operativi per il modello di licensing di ONTAP Select Capacity Pool
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il modello di licenza Capacity Pool è diverso dal modello di Tier di capacità. Invece di dedicare capacità di storage a ciascun nodo, la capacità di storage viene allocata a un pool e condivisa tra più nodi. Sono stati creati ulteriori componenti e processi per supportare il modello dei pool di capacità.



== Manager di licenza

Il Manager di licenza viene eseguito come un processo separato all'interno di ciascuna istanza dell'utilità di amministrazione distribuzione. Alcune delle funzioni fornite da LM includono:

* Genera un numero di serie univoco di venti cifre per ogni nodo in base al numero di serie della licenza Capacity Pool
* Creare leasing per la capacità dai pool di capacità condivisi in base alle richieste provenienti dai nodi ONTAP Select
* Report sulle informazioni di utilizzo del pool tramite l'interfaccia utente di implementazione




== Caratteristiche del leasing

Lo storage allocato per ogni aggregato di dati in un nodo utilizzando una licenza Capacity Pool deve avere un leasing associato. Il nodo richiede un lease dello storage e, se la capacità è disponibile, il Manager di licenza risponde con un lease. Ogni lease ha i seguenti attributi espliciti o impliciti:

* Manager di licenza
+
Ogni nodo ONTAP Select è associato a un'istanza di License Manager

* Pool di capacità
+
Ogni nodo ONTAP Select è associato a un Capacity Pool

* Allocazione dello storage
+
Un valore di capacità specifico viene assegnato nel contratto di locazione

* Data e ora di scadenza
+
I contratti di locazione hanno una durata compresa tra un'ora e sette giorni a seconda della configurazione per l'utente.





== ID blocco licenza

Ogni istanza del Manager di licenza, e quindi ogni istanza dell'utility di implementazione corrispondente, viene identificata con un numero univoco a 128 bit. Questo numero è combinato con il numero seriale della licenza Capacity Pool a nove cifre per bloccare il pool in una specifica istanza di License Manager (che è effettivamente un'istanza di distribuzione). È necessario fornire entrambi i valori nel sito di supporto NetApp come parte della generazione del file di licenza NetApp (NLF).

È possibile determinare l'ID del blocco di licenza per l'istanza di implementazione utilizzando l'interfaccia utente Web nei seguenti modi:

* Pagina iniziale
+
Deploy visualizza questa pagina quando accedi per la prima volta. Puoi anche aprire il menu a discesa in alto a destra della pagina e selezionare *Getting Started* per visualizzare questa pagina. Il LLID viene visualizzato nella sezione Add Licenses.

* Selezionare la scheda *Administration* nella parte superiore della pagina, quindi selezionare *Systems & AutoSupport*.




== Operazioni di leasing di base

Un nodo ONTAP Select deve individuare o richiedere un lease di capacità valido ogni volta che un aggregato di dati viene creato, espanso o modificato. È possibile utilizzare un lease ottenuto da una richiesta precedente ancora valido oppure richiederne uno nuovo, se necessario. Il nodo ONTAP Select esegue i seguenti passaggi per individuare un lease di Capacity Pool:

. Se un lease esistente si trova nel nodo, viene utilizzato purché siano vere tutte le seguenti condizioni:
+
** Il leasing non è scaduto
** La richiesta di storage per l'aggregato non supera la capacità di leasing


. Se non è possibile individuare un lease esistente, il nodo richiede un nuovo lease dal Manager di licenza.




== Consente di restituire la capacità dello storage a un pool di capacità

La capacità dello storage viene allocata da un pool di capacità in base alle necessità e ogni nuova richiesta può ridurre lo storage disponibile nel pool. La capacità dello storage viene restituita al pool in diverse situazioni, tra cui:

* Il lease per un aggregato di dati scade e non viene rinnovato dal nodo
* L'aggregato di dati viene cancellato



NOTE: Se una macchina virtuale ONTAP Select viene eliminata, i lease attivi rimangono in vigore fino alla scadenza. In questo caso, la capacità viene restituita al pool.
