---
sidebar: sidebar 
permalink: concept_lic_cp_benefits.html 
keywords: license, licensing, Capacity Pools, benefits 
summary: 'L"utilizzo del modello di licenza Capacity Pool comporta diversi vantaggi rispetto al modello di licenza Capacity Tiers.' 
---
= Riepilogo dei benefici offerti dalle licenze ONTAP Select Capacity Pool
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'utilizzo del modello di licenza Capacity Pool comporta diversi vantaggi rispetto al modello di licenza Capacity Tiers.



== Utilizzo più efficiente della capacità di storage

Utilizzando la licenza Capacity Tier, viene allocata una capacità dello storage fissa a ciascun nodo. Qualsiasi spazio inutilizzato non può essere condiviso con gli altri nodi e viene effettivamente sprecato. Con la licenza Capacity Pools, ogni nodo consuma solo la capacità di cui ha bisogno, in base alle dimensioni degli aggregati di dati.

Inoltre, poiché la capacità è ancorata in un pool centrale, può essere condivisa tra molti nodi dell'organizzazione.



== Riduzione significativa dell'overhead amministrativo con conseguente riduzione dei costi

Se si utilizzano le licenze Capacity Tier, è necessario ottenere e installare una licenza per ciascun nodo. Quando si utilizzano i pool di capacità, esiste una sola licenza per ogni pool condiviso. Ciò può ridurre drasticamente l'overhead amministrativo e ridurre i costi.



== Metriche di utilizzo migliorate

L'interfaccia utente Web Deploy fornisce informazioni sull'utilizzo avanzate per i pool di capacità. È possibile determinare rapidamente la quantità di storage utilizzata e disponibile in un Capacity Pool, i nodi che utilizzano lo storage di un pool e i pool dai quali un cluster alloca capacità.
