---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: 'È possibile utilizzare una licenza di valutazione se si desidera valutare ONTAP Select prima di prendere la decisione di acquisto. La licenza di valutazione è inclusa nell"utility di amministrazione di ONTAP Select Deploy e viene applicata automaticamente a ciascun nodo ONTAP Select come parte di un"implementazione di valutazione.' 
---
= Licenze di valutazione per implementazioni ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile distribuire ONTAP Select con una licenza di valutazione o una licenza acquistata. La licenza scelta deve essere applicata a ciascun nodo del cluster ONTAP Select e quindi all'intero cluster. È possibile utilizzare una licenza di valutazione se si desidera valutare ONTAP Select prima di prendere la decisione di acquisto. La licenza di valutazione è inclusa nell'utility di amministrazione di ONTAP Select Deploy e viene applicata automaticamente a ciascun nodo ONTAP Select come parte di un'implementazione di valutazione.

[NOTE]
====
Per scaricare l'utilità di amministrazione di distribuzione di ONTAP Select, è necessario disporre di quanto segue:

* Un account registrato sul sito del supporto NetApp. Se non si dispone di un account, vedere https://mysupport.netapp.com/site/user/registration["Registrazione utente"^].
*  https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["Accettare il contratto di licenza per l'utente finale"^]Per una distribuzione ONTAP Select con una licenza di valutazione.


====
Per la distribuzione e il supporto di un cluster di valutazione, è necessario tenere in considerazione i seguenti fattori:

* È possibile utilizzare il cluster solo per scopi di valutazione. Non è necessario utilizzare un cluster con una licenza di valutazione in un ambiente di produzione.
* Per configurare ciascun host, è necessario utilizzare l'utilità di amministrazione di distribuzione di ONTAP Select nel modo seguente:
+
** Non fornire un numero di serie
** Configurare per utilizzare una licenza di valutazione






== Caratteristiche di licensing

La licenza di valutazione ONTAP Select presenta le seguenti caratteristiche:

* Non è necessaria una licenza di produzione con capacità di archiviazione
* Il numero di serie del nodo è composto da venti cifre e viene generato automaticamente dall'implementazione di ONTAP Select
+
(Non lo acquisti direttamente da NetApp)

* Il periodo di valutazione fornito dalla licenza può arrivare fino a 90 giorni
* Lo storage massimo allocato da ciascun nodo è lo stesso di una licenza di produzione




== Aggiornamento a una licenza di produzione

È possibile aggiornare un cluster di valutazione ONTAP Select per utilizzare una licenza di produzione. È necessario conoscere le seguenti restrizioni:

* Per eseguire l'aggiornamento della licenza, è necessario utilizzare l'utility di amministrazione della distribuzione
* È possibile utilizzare una licenza per il livello di capacità, tuttavia la licenza per i pool di capacità non è supportata
* Ogni nodo deve disporre di spazio di storage sufficiente per supportare il minimo richiesto per una licenza di produzione, in base alle dimensioni del cluster


Vedere link:task_adm_licenses.html["Convertire una licenza di valutazione in una licenza di produzione"] per ulteriori informazioni.

.Cosa succederà ora?
* link:access-evaluation-software.html["Accedi al software di valutazione ONTAP Select"]
* link:deploy-evaluation-ontap-select-ovf-template.html["Implementazione di un'istanza di valutazione di 90 giorni di un cluster ONTAP Select"]


.Informazioni correlate
* link:concept_lic_production.html["Scopri di più sulle licenze per le distribuzioni di produzione"]

