---
sidebar: sidebar 
permalink: concept_lic_production.html 
keywords: license, licensing, production, purchased, standard, premium, premium xl 
summary: 'Una volta stabilito che ONTAP Select è adatto alla tua organizzazione, puoi acquistare le licenze necessarie per supportare un"implementazione in produzione. Devi scegliere il modello di licenza per Tier di capacità o pool di capacità, nonché la capacità dello storage per ogni implementazione.' 
---
= ONTAP Select ha acquistato licenze per le implementazioni in produzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una volta stabilito che ONTAP Select è adatto alla tua organizzazione, puoi acquistare le licenze necessarie per supportare un'implementazione in produzione. Devi scegliere il modello di licenza per Tier di capacità o pool di capacità, nonché la capacità dello storage per ogni implementazione.



== Caratteristiche comuni delle licenze

I modelli di licenza _Capacity Tiers_ e _Capacity Pool_ sono molto diversi sotto vari aspetti. Tuttavia, i due modelli di licenza condividono diverse caratteristiche comuni, tra cui:

* Quando si implementa ONTAP Select in un ambiente di produzione, è necessario acquistare una o più licenze in base alle necessità.
* La capacità di storage per una licenza viene allocata in incrementi di 1 TB.
* La capacità di storage identifica la capacità raw e corrisponde alla dimensione totale consentita dei dischi dati disponibili per la macchina virtuale ONTAP Select.
* Sono supportate tutte le offerte di licenze della piattaforma (standard, premium, premium XL).
* Per ricevere assistenza in caso di acquisizione delle licenze necessarie, contatta il tuo account team o partner NetApp.
* È necessario caricare i file di licenza nell'utility di amministrazione di Deploy, che applica le licenze in base al modello di licenza.
* Dopo aver installato e applicato una licenza, è possibile aggiungere ulteriore capacità contattando l'account team o il partner NetApp per ottenere una licenza aggiornata.
* Entrambi i nodi di una coppia ha devono avere la stessa capacità di storage e licenza.
* Un nodo ONTAP Select inizialmente implementato con una licenza acquistata non può essere convertito in una licenza di valutazione.




== Modello di licensing basato su Tier di capacità

Il modello di licenza per Tier di capacità presenta diverse caratteristiche, tra cui:

* È necessario acquistare una licenza per ciascun nodo ONTAP Select.
* L'importo minimo che puoi acquistare è di 1 TB.
* Ogni licenza Capacity Tier ha una capacità di storage e viene bloccata in un nodo specifico.
* NetApp genera un numero seriale di nove cifre per ogni nodo ONTAP Select.
* Lo storage allocato a un nodo è perpetuo (non è richiesto alcun rinnovo).
* Il numero di serie del nodo è composto da nove cifre e corrisponde al numero di serie della licenza.
* È possibile applicare il file di licenza durante l'implementazione del cluster o entro 30 giorni dalla creazione di un cluster.




== Modello di licensing basato sulla capacità

Il modello di licenza Capacity Pool presenta diverse caratteristiche, tra cui:

* Devi acquistare una licenza per ogni pool di capacità condiviso.
* L'importo minimo che puoi acquistare è di 2 TB.
* Ogni licenza Capacity Pool ha una capacità di storage ed è bloccata su una specifica istanza di License Manager.
* NetApp genera un numero di serie della licenza a nove cifre per ogni pool di capacità.
* Lo storage allocato a un pool di capacità è valido solo per un periodo specifico in base all'acquisto (è richiesto un rinnovo).
* Il numero di serie del nodo è di venti cifre e viene generato dal Manager di licenza in base al numero di serie della licenza di Capacity Pool.
* Ogni nodo concede in leasing automatico la capacità dello storage per gli aggregati di dati locali da un pool di capacità condiviso.


Per ulteriori informazioni sul modello di licenza dei pool di capacità, vedere _modello di licenza dei pool di capacità_ per ulteriori informazioni.
