---
sidebar: sidebar 
permalink: concept_lic_cp_benefits.html 
keywords: license, licensing, capacity pools, benefits 
summary: 'L"utilizzo del modello di licensing dei pool di capacità offre diversi vantaggi invece del modello di licensing dei Tier di capacità.' 
---
= Riepilogo dei benefici
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'utilizzo del modello di licensing dei pool di capacità offre diversi vantaggi invece del modello di licensing dei Tier di capacità.



== Utilizzo più efficiente della capacità di storage

Quando si utilizzano i livelli di licenza della capacità, viene allocata una capacità di storage fissa a ciascun nodo. Qualsiasi spazio inutilizzato non può essere condiviso con gli altri nodi e viene effettivamente sprecato. Con le licenze per i pool di capacità, ogni nodo consuma solo la capacità necessaria, in base alle dimensioni degli aggregati di dati.

Inoltre, poiché la capacità è ancorata in un pool centrale, può essere condivisa tra molti nodi dell'organizzazione.



== Riduzione significativa dell'overhead amministrativo con conseguente riduzione dei costi

Se si utilizzano licenze di livello di capacità, è necessario ottenere e installare una licenza per ciascun nodo. Quando si utilizzano i pool di capacità, è disponibile una licenza per ciascun pool condiviso. Ciò può ridurre drasticamente l'overhead amministrativo e ridurre i costi.



== Metriche di utilizzo migliorate

L'interfaccia utente Web di implementazione fornisce informazioni di utilizzo avanzate per i pool di capacità. È possibile determinare rapidamente la quantità di storage utilizzata e disponibile in un pool di capacità, i nodi che utilizzano lo storage di un pool e i pool da cui un cluster sta allocando la capacità.
