---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: La versione corrente include diverse nuove funzioni o miglioramenti specifici di ONTAP Select. 
---
= Le novità di ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le nuove funzioni e i miglioramenti delle versioni supportate di ONTAP Select.



== ONTAP Select 9.17.1

ONTAP Select 9.17.1 include numerose nuove funzionalità e miglioramenti.

Supporto RAID software per dischi NVMe collegati localmente su host KVM:: ONTAP Select 9.17.1 introduce il supporto RAID software per i dischi NVMe ONTAP Select collegati localmente su un host hypervisor KVM (Kernel-Based Virtual Machine).
+
--
Per utilizzare il RAID software per i dischi NVMe collegati localmente, è necessario link:kvm-host-configuration-and-preparation-checklist.html["configurare il passthrough PCI (DirectPath IO)"] durante la preparazione dell'host KVM. Ciò fornisce all'host KVM l'accesso diretto ai dischi NVMe collegati localmente, necessario per le seguenti attività:

* Configurazione dell'host KVM per l'utilizzo di unità NVMe
* Utilizzo del software RAID dopo aver distribuito il cluster


link:concept_stor_swraid_local.html["Scopri di più sui servizi di configurazione RAID software per l'archiviazione locale collegata"] .

--
Supporto per l'espansione e la contrazione del cluster sugli host KVM:: A partire da ONTAP Select 9.17.1, la funzionalità di espansione e contrazione dei cluster è supportata sia per gli host KVM (Kernel-Based Virtual Machine) che per gli host hypervisor ESXi. Per ONTAP Select 9.16.1 e 9.15.1, l'espansione e la contrazione dei cluster sono supportate solo per gli host hypervisor ESXi.
+
--
È possibile utilizzare la funzionalità di espansione e contrazione del cluster su un cluster ONTAP Select esistente per aumentare le dimensioni da un cluster a sei nodi a uno a otto nodi o per ridurle da un cluster a otto nodi a uno a sei nodi.

link:task_cluster_expansion_contraction.html["Scopri di più sull'espansione e la contrazione del cluster e sulle versioni supportate degli hypervisor KVM ed ESXi"] .

--
Supporto migliorato per l'espansione e la contrazione del cluster sugli host ESXi:: A partire da ONTAP Select 9.17.1, l'espansione e la contrazione del cluster sono supportate per cluster da sei a dodici nodi su host ESXi:
+
--
--
È possibile aumentare le dimensioni del cluster per un cluster ESXi esistente nei seguenti incrementi:

* Da sei nodi a otto, dieci o dodici nodi
* Da otto nodi a dieci o dodici nodi
* Da dieci a dodici nodi


È possibile ridurre le dimensioni del cluster per un cluster ESXi esistente nei seguenti incrementi:

* Da dodici nodi a dieci, otto o sei nodi
* Da dieci nodi a otto o sei nodi
* Da otto a sei nodi


--
link:task_cluster_expansion_contraction.html["Scopri di più sull'espansione e la contrazione del cluster e sulle versioni supportate degli hypervisor KVM ed ESXi"] .

--
Supporto per il cloud SnapMirror:: A partire da ONTAP Select 9.17.1, SnapMirror Cloud è supportato da ONTAP Select. SnapMirror Cloud è una funzionalità ONTAP concessa in licenza, abilitata per impostazione predefinita quando si distribuisce un cluster ONTAP Select 9.17.1 o si aggiorna un cluster ONTAP Select esistente alla versione 9.17.1.
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["Scopri di più sui backup cloud SnapMirror su storage di oggetti"^] .

--
Supporto per SnapLock Select Enterprise:: A partire da ONTAP Select 9.17.1, le nuove distribuzioni dispongono automaticamente della licenza SnapLock Select Enterprise (incluso il blocco snapshot antimanomissione).  Per gli aggiornamenti da ONTAP Select 9.16.1 e versioni precedenti, è necessario scaricare la licenza SnapLock Select dalink:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] e applicarlo manualmente.
Supporto per vSAN ESA su cluster multi-nodo:: A partire da ONTAP Select 9.17.1, il supporto per vSAN Express Storage Architecture (ESA) è esteso per distribuire cluster multi-nodo.  Questo miglioramento consente di distribuire configurazioni vSAN ESA.
+
--
vSAN ESA è una configurazione specifica di ESX e una nuova architettura per VMware vSAN introdotta in vSphere 8. vSAN ESA è progettato per offrire maggiore efficienza, scalabilità e prestazioni, in particolare quando si utilizzano dispositivi flash TLC basati su NVMe.

ONTAP Select Deploy e ONTAP Select per ESX supportano la configurazione di un cluster ONTAP Select a nodo singolo e multi-nodo, utilizzando un vSAN o un tipo di datastore di array esterno per il suo pool di archiviazione.

[NOTE]
====
Per eseguire operazioni sulla libreria dei contenuti, è necessario accedere a livelli di autorizzazione aggiuntivi.  Questa operazione è necessaria per le distribuzioni vSAN ESA se si lavora con ruoli limitati.

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["Scopri come accedere ai livelli di autorizzazione per le operazioni della libreria di contenuti"^] .

====
--
Supporto driver NDA aggiornato:: A partire da ONTAP Select 9.17.1, il driver di dispositivo NDA (NVMe Direct Access) di FreeBSD sostituisce il driver NVD (NVMe Express Disk Driver). Il driver di FreeBSD fornisce supporto per i dispositivi ad accesso diretto implementando il protocollo di comando NVMe. Quando si distribuisce un cluster ONTAP Select 9.17.1 o si aggiorna un cluster ONTAP Select esistente alla versione 9.17.1, il driver di FreeBSD viene avviato per impostazione predefinita durante la configurazione dei dispositivi NVMe.
+
--
Per ONTAP Select 9.16.1 e versioni precedenti, NVD continua a fornire supporto per i dispositivi NVMe nella distribuzione ONTAP Select .

--
Supporto aggiornato dell'hypervisor KVM:: A partire da ONTAP Select 9.17.1, l'hypervisor KVM è supportato su Red Hat Enterprise Linux (RHEL) 9.6 e Rocky Linux 9.6.
Supporto migliorato di VMware ESXi:: ONTAP Select 9.17.1 include il supporto per VMware ESXi 9.0.




== ONTAP Select 9.16.1

ONTAP Select 9.16.1 include diverse nuove funzioni e miglioramenti.

Supporto file di licenza NetApp aggiornato:: A partire da ONTAP Select 9.16.1, viene aggiornato il supporto del file di licenza NetApp (NLF). Il nuovo formato NLF include le licenze per le funzioni ARP, ONTAP S3 e S3 SnapMirror. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Scopri di più"].
+
--
Per una nuova implementazione di ONTAP Select 9.16.1, viene applicato automaticamente il nuovo formato NLF. Quando si aggiorna una distribuzione ONTAP Select esistente a 9.16.1, il nuovo formato NLF non viene applicato. Per ottenere le licenze ARP, ONTAP S3 e S3 SnapMirror Feature, è necessario scaricare l'NLF aggiornato dopo l'aggiornamento. Se si torna a ONTAP Select 9.15.1 o versioni precedenti, è necessario reinstallare le licenze delle funzioni prima dell'aggiornamento.

--
Supporto per la protezione autonoma da ransomware:: ONTAP Select 9.16.1 introduce il supporto per la protezione autonoma dal ransomware (ARP). ONTAP Select 9.16.1 supporta solo gli aggiornamenti manuali per ARP, gli aggiornamenti automatici non sono supportati. La licenza della funzione ARP è inclusa nell'NLF per ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Scopri di più"].
Supporto migliorato di VMware ESXi:: ONTAP Select 9.16.1 include il supporto per VMware ESXi 8.0 U3.
Supporto aggiornato dell'hypervisor KVM:: A partire da ONTAP Select 9.16.1, l'hypervisor KVM è supportato su RHEL 9.5 e Rocky Linux 9.5.




== ONTAP Select 9.15.1

ONTAP Select 9.15.1 include diverse nuove funzioni e miglioramenti.

Supporto aggiornato dell'hypervisor KVM:: A partire da ONTAP Select 9.15.1, l'hypervisor kernel-Based Virtual Machine (KVM) è supportato su RHEL 9,4 e Rocky Linux 9,4.
Supporto dell'espansione e della contrazione dei cluster:: A partire da ONTAP Select 9.15.1 sono supportate l'espansione e la contrazione del cluster.
+
--
* Espansione del cluster da cluster a 6 nodi a 8 nodi
+
Grazie alla funzionalità di espansione del cluster, è possibile aumentare le dimensioni del cluster da un cluster a sei nodi a un cluster a otto nodi. Al momento non sono supportate le espansioni del cluster da uno, due o quattro nodi a cluster a sei o otto nodi. link:task_cluster_expansion_contraction.html#expand-the-cluster["Scopri di più"].

* Cluster con contrazione da 8 nodi a 6 nodi
+
Grazie alla funzionalità di contrazione del cluster, è possibile diminuire le dimensioni del cluster da un cluster a otto nodi a un cluster a sei nodi. Le contrazioni del cluster da cluster a sei o otto nodi a uno, due o quattro nodi non sono attualmente supportate. link:task_cluster_expansion_contraction.html#contract-the-cluster["Scopri di più"].



--



NOTE: Il supporto per l'espansione e la contrazione dei cluster è limitato solo ai cluster ESX.



== ONTAP Select 9.14.1

ONTAP Select 9.14.1 include diverse nuove funzioni e miglioramenti.

Supporto dell'hypervisor KVM:: A partire da ONTAP Select 9.14.1, il supporto per l'hypervisor KVM è stato ripristinato. In precedenza, il supporto per l'implementazione di un nuovo cluster su un hypervisor KVM è stato rimosso in ONTAP Select 9.10.1 e il supporto per la gestione di cluster e host KVM esistenti, ad eccezione di quelli da mettere offline o eliminare, è stato rimosso in ONTAP Select 9.11.1.
L'implementazione del plug-in VMware vCenter non è più supportata:: A partire da ONTAP Select 9.14.1, il plug-in Deploy VMware vCenter non è più supportato.
Supporto di distribuzione ONTAP Select aggiornato:: Se si sta eseguendo una versione di ONTAP Select Deploy 9.14.1 inferiore a 9.14.1P2, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 non appena possibile. Per ulteriori informazioni, consultare link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione di ONTAP Select 9.14.1"^].
Supporto migliorato di VMware ESXi:: ONTAP Select 9.14.1 include il supporto per VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

ONTAP Select 9.13.1 include diverse nuove funzioni e miglioramenti.

Supporto di NVMe over TCP:: Quando esegui l'upgrade a ONTAP Select 9.13.1, devi disporre della nuova licenza per supportare NVMe su TCP. Questa licenza viene inclusa automaticamente quando si distribuisce ONTAP Select per la prima volta dalla versione 9.13.1.
Supporto VMware ESXi aggiornato:: A partire da ONTAP 9.13,1, VMware ESXi 8.0.1 GA (build 20513097) è supportato con la versione hardware 4 e successive.
Supporto di distribuzione ONTAP Select aggiornato:: A partire da aprile 2024, ONTAP Select Deployment 9.13.1 non sarà più disponibile sul sito di supporto NetApp. Se si esegue ONTAP Select Deploy 9.13.1, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 il prima possibile. Per ulteriori informazioni, consultare link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione di ONTAP Select 9.14.1"^].




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 beneficia della maggior parte dei nuovi sviluppi della release corrente del prodotto ONTAP principale. Non include nuove funzioni o miglioramenti specifici di ONTAP Select.

A partire da aprile 2024, ONTAP Select Deployment 9.12.1 non sarà più disponibile sul sito di supporto NetApp. Se si esegue ONTAP Select Deploy 9.12.1, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 il prima possibile. Per ulteriori informazioni, consultare link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione di ONTAP Select 9.14.1"^].



== ONTAP Select 9.11.1

ONTAP Select 9.11.1 include diverse nuove funzionalità e miglioramenti.

Supporto migliorato di VMware ESXi:: ONTAP Select 9.11.1 include il supporto per VMware ESXi 7.0 U3C.
Supporto per VMware NSX-T.:: ONTAP Select 9.10.1 e le versioni successive sono qualificate per VMware NSX-T versione 3.1.2. Non ci sono problemi funzionali o difetti quando si utilizza NSX-T con un cluster a nodo singolo ONTAP Select implementato con un file OVA e l'utility di amministrazione di ONTAP Select Deploy. Tuttavia, quando si utilizza NSX-T con un cluster a più nodi ONTAP Select, è necessario tenere presente il seguente limite per ONTAP Select 9.11.1:
+
--
* Strumento di controllo della connettività di rete
+
Il controllo della connettività di rete disponibile tramite la CLI di implementazione non riesce quando viene eseguito su una rete basata su NSX-T.



--
L'hypervisor KVM non è più supportato::
+
--
* A partire da ONTAP Select 9.10.1, non è più possibile implementare un nuovo cluster sull'hypervisor KVM.
* A partire da ONTAP Select 9.11.1, tutte le funzionalità di gestibilità non sono più disponibili per i cluster e gli host KVM esistenti, ad eccezione delle funzioni take offline e delete.
+
NetApp consiglia vivamente ai clienti di pianificare ed eseguire una migrazione completa dei dati da ONTAP Select per KVM a qualsiasi altra piattaforma ONTAP, incluso ONTAP Select per ESXi. Per ulteriori informazioni, consultare https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Avviso EOA"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1 include diverse nuove funzionalità e miglioramenti.

Supporto per VMware NSX-T.:: ONTAP Select 9.10.1 è stato qualificato per VMware NSX-T versione 3.1.2. Non ci sono problemi funzionali o difetti quando si utilizza NSX-T con un cluster a nodo singolo ONTAP Select implementato con un file OVA e l'utility di amministrazione di ONTAP Select Deploy. Tuttavia, quando si utilizza NSX-T con un cluster a più nodi ONTAP Select, è necessario tenere presenti i seguenti requisiti e limitazioni:
+
--
* MTU del cluster
+
È necessario regolare manualmente la dimensione MTU del cluster su 8800 prima di implementare il cluster per tenere conto dell'overhead aggiuntivo. La guida di VMware è quella di consentire un buffer da 200 byte quando si utilizza NSX-T.

* Configurazione di rete 4x10 GB
+
Per le implementazioni ONTAP Select su un host VMware ESXi configurato con quattro NIC, l'utility di implementazione richiede di seguire la procedura consigliata per suddividere il traffico interno tra due diversi gruppi di porte e il traffico esterno tra due diversi gruppi di porte. Tuttavia, quando si utilizza una rete sovrapposta, questa configurazione non funziona e si consiglia di non seguire questa raccomandazione. In questo caso, utilizzare un solo gruppo di porte interno e un solo gruppo di porte esterno.

* Strumento di controllo della connettività di rete
+
Il controllo della connettività di rete disponibile tramite la CLI di implementazione non riesce quando viene eseguito su una rete basata su NSX-T.



--
L'hypervisor KVM non è più supportato:: A partire da ONTAP Select 9.10.1, non è più possibile implementare un nuovo cluster sull'hypervisor KVM. Tuttavia, se si aggiorna un cluster da una release precedente a 9.10.1, è comunque possibile utilizzare l'utility di distribuzione per amministrare il cluster.




== ONTAP Select 9.9.1

ONTAP Select 9.9.1 include diverse nuove funzionalità e miglioramenti.

Supporto per la famiglia di processori:: A partire da ONTAP Select 9,9.1, per ONTAP Select sono supportati solo i modelli di CPU di Intel Xeon Sandy Bridge o versioni successive.
Supporto VMware ESXi aggiornato:: Il supporto per VMware ESXi è stato migliorato con ONTAP Select 9.9.1. Sono ora supportate le seguenti versioni:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8 include diverse funzionalità nuove e modificate.

Interfaccia ad alta velocità:: L'interfaccia ad alta velocità migliora la connettività di rete offrendo un'opzione per 25G (25 GbE) e 40G (40 GbE). Per ottenere le migliori prestazioni quando si utilizzano queste velocità più elevate, seguire le Best practice relative alle configurazioni di mappatura delle porte descritte nella documentazione di ONTAP Select.
Supporto VMware ESXi aggiornato:: Sono state apportate due modifiche a ONTAP Select 9.8 per quanto riguarda il supporto di VMware ESXi.
+
--
* È supportato ESXi 7.0 (GA build 15843807 e versioni successive)
* ESXi 6.0 non è più supportato


--

