---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: È necessario considerare diversi problemi di pianificazione relativi allo storage host ONTAP Select. 
---
= Considerazioni su storage e RAID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario considerare diversi problemi di pianificazione relativi allo storage host ONTAP Select.


NOTE: Le informazioni sul supporto dello storage esterno sono riportate nella link:reference_plan_ots_vnas.html["Requisiti di ONTAP Select vNAS"].



== Requisiti del controller RAID hardware

Il controller RAID sull'host dell'hypervisor in cui si implementa ONTAP Select deve soddisfare diversi requisiti.


NOTE: Un host ESXi in cui viene eseguito ONTAP Select richiede dischi fisici locali quando si utilizza un controller RAID hardware o la funzionalità RAID software fornita con ONTAP Select. Se si utilizza la soluzione ONTAP Select vNAS per accedere allo storage esterno, non vengono utilizzati un controller RAID locale e la funzionalità RAID software.

I requisiti minimi per il controller RAID includono:

* Throughput a 12 Gbps
* 512 MB di cache interna con batteria tampone o flash (SuperCAP)
* Configurato in modalità write-back:
+
** Abilitare la modalità di failback su "write through" (se supportata)
** Abilitare la policy "always Read ahead" (se supportata)


* Tutti i dischi locali dietro il controller RAID devono essere configurati come un singolo gruppo RAID; se necessario, è possibile utilizzare più controller RAID:
+
** Disattivare la cache del disco locale per il gruppo RAID, fondamentale per preservare l'integrità dei dati.


* La configurazione del LUN deve essere eseguita in base alle seguenti linee guida:
+
** Se la dimensione del gruppo RAID supera la dimensione massima del LUN ESXi di 64 TB, è necessario configurare più LUN di pari dimensioni che consumano tutto lo storage disponibile all'interno del gruppo RAID.
** Se la dimensione del gruppo RAID è inferiore alla dimensione massima del LUN ESXi di 64 TB, è necessario configurare un LUN che utilizzi tutto lo storage disponibile all'interno del gruppo RAID.






== Requisiti RAID software

Quando si implementa un cluster ONTAP Select sull'hypervisor VMware ESXi, è possibile utilizzare la funzionalità RAID software fornita da ONTAP Select invece di un controller RAID hardware locale. Prima di implementare un cluster utilizzando il RAID software, è necessario conoscere diversi requisiti e restrizioni.



=== Requisiti generali

L'ambiente per un'implementazione RAID software su VMware ESXi deve soddisfare i seguenti requisiti fondamentali:

* VMware ESXi 7,0 GA (build 15843807) o versione successiva
* ONTAP Select 9.5 o versione successiva
* ONTAP Select Deploy 2.10 o versione successiva
* Solo nuovi cluster ONTAP Select



NOTE: È necessario implementare un nuovo cluster con ONTAP Select 9.5 o versione successiva, utilizzando l'utility di amministrazione di Deploy. Non è possibile utilizzare il RAID software con un nodo esistente che è stato aggiornato da una versione precedente a ONTAP Select 9.5.

* Licenza Premium ONTAP Select o superiore
* Solo unità SSD locali
* Separazione dei dischi di sistema dagli aggregati root e dati
* Nessun controller RAID hardware sull'host



NOTE: Se è presente un controller RAID hardware, consultare link:concept_stor_concepts_chars.html["Storage per immersioni profonde"] per ulteriori requisiti di configurazione.

* VMware VMotion, ha e DRS non sono supportati




=== Configurazione del nodo ONTAP Select

Per separare i dischi di sistema dagli aggregati di dati e root, è necessario configurare ciascun nodo ONTAP Select e l'host dell'hypervisor come segue:

* Creare un pool di storage di sistema è necessario creare un pool di storage per i dati di sistema di ONTAP Select. È necessario collegare il pool di storage durante la configurazione del nodo ONTAP Select.
* Collegare i dischi fisici necessari l'host dell'hypervisor deve avere i dischi SSD necessari collegati e disponibili per l'utilizzo da parte della macchina virtuale ONTAP Select. Questi dischi conservano gli aggregati root e di dati. È necessario collegare i dischi di storage durante la configurazione del nodo ONTAP Select.




== Limitazioni della capacità dello storage

Nell'ambito della pianificazione di un'implementazione di ONTAP Select, è necessario conoscere le restrizioni relative all'utilizzo e all'allocazione dello storage.

Di seguito sono illustrate le principali restrizioni di storage. Per informazioni più dettagliate, consulta anche il _NetApp Interoperability Matrix Tool_.


TIP: ONTAP Select applica diverse restrizioni relative all'allocazione e all'utilizzo dello storage. Prima di implementare un cluster ONTAP Select o di acquistare una licenza, è necessario conoscere tali limitazioni. Per ulteriori informazioni, consultare la sezione _licenza_.



=== Calcolo della capacità di storage raw

La capacità dello storage ONTAP Select corrisponde alla dimensione totale consentita dei dati virtuali e dei dischi root collegati alla macchina virtuale ONTAP Select. È necessario tenere in considerazione questo aspetto quando si assegna la capacità.



=== Capacità di storage minima per un cluster a nodo singolo

La dimensione minima del pool di storage allocato per il nodo in un cluster a nodo singolo è:

* Valutazione: 500 GB
* Produzione: 1.0 TB


L'allocazione minima per un'implementazione in produzione consiste di 1 TB per i dati dell'utente, più circa 266 GB utilizzati da vari processi interni di ONTAP Select, che viene considerato un overhead richiesto.



=== Capacità di storage minima per un cluster multi-nodo

La dimensione minima del pool di storage allocato per ciascun nodo in un cluster a più nodi è:

* Valutazione: 1.9 TB
* Produzione: 2.0 TB


L'allocazione minima per un'implementazione in produzione consiste di 2 TB per i dati utente, più circa 266 GB utilizzati da vari processi interni ONTAP Select, che viene considerato un overhead richiesto.


NOTE: Ogni nodo di una coppia ha deve avere la stessa capacità di storage.



=== Capacità dello storage e più pool di storage

È possibile configurare ciascun nodo ONTAP Select in modo che utilizzi fino a 400 TB di storage quando si utilizzano storage direct-attached locale, VMware vSAN o storage array esterni. Tuttavia, un singolo pool di storage ha una dimensione massima di 64 TB quando si utilizzano storage direct-attached o array di storage esterni. Pertanto, se si prevede di utilizzare più di 64 TB di storage in queste situazioni, è necessario allocare più pool di storage come segue:

* Assegnare il pool di storage iniziale durante il processo di creazione del cluster
* Aumentare lo storage del nodo allocando uno o più pool di storage aggiuntivi



NOTE: Un buffer del 2% viene lasciato inutilizzato in ogni pool di storage e non richiede una licenza di capacità. Questo storage non viene utilizzato da ONTAP Select, a meno che non venga specificato un limite di capacità. Se viene specificato un limite massimo di capacità, la quantità di storage verrà utilizzata a meno che la quantità specificata non rientri nella zona di buffer del 2%. Il buffer è necessario per evitare errori occasionali che si verificano quando si tenta di allocare tutto lo spazio in un pool di storage.



=== Capacità dello storage e VMware vSAN

Quando si utilizza VMware vSAN, un datastore può superare i 64 TB. Tuttavia, è possibile allocare solo inizialmente fino a 64 TB quando si crea il cluster ONTAP Select. Una volta creato il cluster, è possibile allocare ulteriore storage dal datastore vSAN esistente. La capacità del datastore vSAN che può essere consumata da ONTAP Select si basa sul set di criteri di storage delle macchine virtuali.



=== Best practice

Si consiglia di prendere in considerazione i seguenti consigli relativi all'hardware di base dell'hypervisor:

* Tutti i dischi di un singolo aggregato ONTAP Select devono essere dello stesso tipo. Ad esempio, non si dovrebbero combinare dischi HDD e SSD nello stesso aggregato.




== Requisiti aggiuntivi per i dischi in base alla licenza della piattaforma

I dischi scelti sono limitati in base all'offerta di licenza della piattaforma.


NOTE: I requisiti dei dischi si applicano quando si utilizzano dischi e controller RAID locali, oltre che RAID software. Questi requisiti non si applicano allo storage esterno a cui si accede tramite la soluzione vNAS di ONTAP Select.

.Standard
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)


.Premium
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)
* Da 4 a 60 SSD interni


.Premium XL
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)
* Da 4 a 60 SSD interni
* Da 4 a 14 NVMe interni



NOTE: Il RAID software con dischi DAS locali è supportato con la licenza Premium (solo SSD) e la licenza Premium XL (SSD o NVMe).



== Dischi NVMe con RAID software

È possibile configurare il RAID software per l'utilizzo di unità SSD NVMe. L'ambiente deve soddisfare i seguenti requisiti:

* ONTAP Select 9.7 o versione successiva con l'utility di amministrazione della distribuzione associata
* Offerta di licenza per piattaforma Premium XL o licenza di valutazione per 90 giorni
* VMware ESXi versione 6.7 o successiva
* Dispositivi NVMe conformi alla specifica 1.0 o successiva


È necessario configurare manualmente i dischi NVMe prima di utilizzarli. Vedere link:task_chk_nvme_configure.html["Configurazione di un host per l'utilizzo di dischi NVMe"] per ulteriori informazioni.
