---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select offre il supporto completo per la maggior parte delle funzionalità ONTAP. Molte delle funzionalità di ONTAP vengono concesse in licenza automaticamente per ogni nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata. 
---
= Supporto ONTAP Select per le funzionalità ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select supporta la maggior parte delle funzionalità ONTAP . Molte delle funzionalità ONTAP vengono concesse in licenza automaticamente per ciascun nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata.


NOTE: Le funzionalità di ONTAP con dipendenze specifiche dell'hardware non sono generalmente supportate con ONTAP Select.



== Funzionalità ONTAP con licenza predefinita

Le seguenti funzioni di ONTAP sono supportate con ONTAP Select e concesse in licenza per impostazione predefinita:

* Protezione autonoma dal ransomware (ARP) (aggiornamenti manuali)
* CIFS
* Deduplica e compressione
* Gestione delle chiavi esterne utilizzando il Key Management Interoperability Protocol (KMIP)
+
La gestione delle chiavi esterne è l'unica gestione delle chiavi supportata da ONTAP Select. Scopri di più link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["abilitazione e configurazione della gestione delle chiavi esterne"^].

* FlexCache
+
ONTAP Select supporta i volumi cache FlexCache con write-back. I volumi origin FlexCache con write-back non sono supportati.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["Scopri di più sulla funzione di write-back di FlexCache con ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (solo paesi non soggetti a restrizioni)
* NFS
* NVMe su TCP
* Funzionalità di multi-tenancy ONTAP
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select è l'implementazione di ONTAP SnapLock progettata per ONTAP Select e include SnapLock Enterprise. Non include SnapLock Compliance.

+
Scopri di piùlink:https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock"^]

* SnapMirror
* SnapRestore
* SnapVault
* Disaster recovery delle macchine virtuali storage (DR SVM)
+
ONTAP Select supporta SVM DR sia come sorgente che come destinazione, con un massimo di 16 relazioni. Il supporto SVM DR è limitato all'utilizzo della versione di ONTAP sorgente fino a versioni +2. Ad esempio, la sorgente ONTAP Select 9.16.1 può connettersi alle destinazioni ONTAP versioni 9.16.1, 9.17.1 o 9.18.1.





== Funzionalità ONTAP con licenza separata

È necessario acquisire una licenza separata per qualsiasi funzionalità di ONTAP non inclusa nella licenza predefinita, tra cui:

* FabricPool
+

NOTE: Non è necessaria una licenza FabricPool quando si utilizza StorageGRID.

* SDS MetroCluster (offerta di licenze premium ONTAP Select)
* SnapMirror cloud
+
È necessario link:https://mysupport.netapp.com/site/help["aprire una richiesta di assistenza non tecnica"^] per ottenere una licenza cloud SnapMirror.

+
Scopri di piùlink:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["SnapMirror cloud backup su storage a oggetti"^]



.Informazioni correlate
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Confrontare ONTAP Select e ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Scopri le chiavi di licenza master NetApp ONTAP"^]

