---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select offre il supporto completo per la maggior parte delle funzionalità ONTAP. Molte delle funzionalità di ONTAP vengono concesse in licenza automaticamente per ogni nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata. 
---
= Supporto ONTAP Select per le funzionalità ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select supporta la maggior parte delle funzionalità ONTAP . Molte delle funzionalità ONTAP vengono concesse in licenza automaticamente per ciascun nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata.


NOTE: Le funzionalità di ONTAP con dipendenze specifiche dell'hardware non sono generalmente supportate con ONTAP Select.



== Le funzioni ONTAP sono attivate automaticamente per impostazione predefinita

Le seguenti funzioni di ONTAP sono supportate con ONTAP Select e concesse in licenza per impostazione predefinita:

* Protezione autonoma dal ransomware (ARP) (aggiornamenti manuali)
* CIFS
* Deduplica e compressione
* FlexCache
+
ONTAP Select supporta i volumi cache FlexCache con write-back. I volumi origin FlexCache con write-back non sono supportati.

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["Scopri di più sulla funzione di write-back di FlexCache con ONTAP Select"]

* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (solo paesi non soggetti a restrizioni)
* NFS
* NVMe su TCP
* Funzionalità di multi-tenancy ONTAP
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select è l'implementazione di ONTAP SnapLock progettata per ONTAP Select e include SnapLock Enterprise. Non include SnapLock Compliance.

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["Scopri ONTAP SnapLock"^]

* SnapMirror
* SnapMirror cloud
* SnapRestore
* SnapVault
* Disaster recovery delle macchine virtuali storage (DR SVM)
+
ONTAP Select supporta DR SVM come origine e destinazione, con un massimo di 16 relazioni. Il supporto DR SVM è limitato all'utilizzo della versione ONTAP di origine alle versioni +2. Ad esempio, l'origine ONTAP Select 9.12.1 può connettersi alle versioni di ONTAP di destinazione 9.12.1, 9.13.1 o 9.14.1.





== Funzionalità ONTAP con licenza separata

È necessario acquistare una licenza separata per qualsiasi funzionalità ONTAP non abilitata per impostazione predefinita, tra cui:

* FabricPool
+

NOTE: Non è necessaria una licenza FabricPool quando si utilizza StorageGRID.

* SDS MetroCluster (offerta di licenze premium ONTAP Select)


.Informazioni correlate
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["Confrontare ONTAP Select e ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Scopri le chiavi di licenza master di NetApp ONTAP"^]

