---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select offre il supporto completo per la maggior parte delle funzionalità ONTAP. Molte delle funzionalità di ONTAP vengono concesse in licenza automaticamente per ogni nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata. 
---
= Funzionalità di ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select offre il supporto completo per la maggior parte delle funzionalità ONTAP. Molte delle funzionalità di ONTAP vengono concesse in licenza automaticamente per ogni nodo quando si implementa un cluster. Tuttavia, alcune funzionalità richiedono una licenza separata.


NOTE: Le funzionalità di ONTAP con dipendenze specifiche dell'hardware non sono generalmente supportate con ONTAP Select.



== Le funzioni ONTAP sono attivate automaticamente per impostazione predefinita

Le seguenti funzioni sono incluse in ONTAP Select e concesse in licenza per impostazione predefinita:

* CIFS
* Deduplica e compressione
* FlexCache
* FlexClone
* ISCSI
* NDMP
* NetApp Volume Encryption (solo paesi non soggetti a restrizioni)
* NFS
* NVMe su TCP
* Funzionalità di multi-tenancy ONTAP
* SnapMirror
* SnapRestore
* SnapVault
* Disaster recovery delle macchine virtuali storage (DR SVM)
+

NOTE: ONTAP Select 9.12.1 (e versioni successive) ora supporta DR SVM come origine e destinazione, con un massimo di 16 relazioni. Il supporto DR SVM è limitato all'utilizzo della versione ONTAP di origine alle versioni +2. Ad esempio, l'origine ONTAP Select 9.12.1 può connettersi alle versioni di ONTAP di destinazione 9.12.1, 9.13.1 o 9.14.1.





== Funzionalità ONTAP con licenza separata

È necessario acquistare una licenza separata per qualsiasi funzione ONTAP non attivata per impostazione predefinita, tra cui:

* Servizio di disponibilità dei dati
* FabricPool
* SDS MetroCluster (offerta di licenze premium ONTAP Select)
* ONTAP S3 (costo zero)
* SnapLock Enterprise (la conformità SnapLock non è supportata per ONTAP Select)
+
** Copie Snapshot a prova di manomissione


* SyncMirror (costo zero)



NOTE: Non è necessaria una licenza FabricPool quando si utilizza StorageGRID webscale.

.Informazioni correlate
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["Confronto tra ONTAP Select e ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["Chiavi di licenza master NetApp ONTAP"^]

