---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: È necessario considerare diversi problemi di pianificazione relativi allo storage host ONTAP Select. 
---
= Considerazioni su storage ONTAP Select e RAID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario considerare diversi problemi di pianificazione relativi allo storage host ONTAP Select.


NOTE: Le informazioni sul supporto dello storage esterno sono riportate nella link:reference_plan_ots_vnas.html["Requisiti di ONTAP Select vNAS"].



== Requisiti del controller RAID hardware

Il controller RAID sull'host dell'hypervisor in cui si implementa ONTAP Select deve soddisfare diversi requisiti.


NOTE: Un host in cui è in esecuzione ONTAP Select richiede unità fisiche locali quando si utilizza un controller RAID hardware o la funzionalità RAID software fornita con ONTAP Select. Se si utilizza la soluzione ONTAP Select vNAS per accedere allo storage esterno, non vengono utilizzati un controller RAID locale e la funzionalità RAID software.

I requisiti minimi per il controller RAID includono:

* Throughput a 12 Gbps
* 512 MB di cache interna con batteria tampone o flash (SuperCAP)
* Configurato in modalità write-back:
+
** Abilitare la modalità di failback su "write through" (se supportata)
** Abilitare la policy "always Read ahead" (se supportata)


* Tutti i dischi locali dietro il controller RAID devono essere configurati come un singolo gruppo RAID; se necessario, è possibile utilizzare più controller RAID:
+
** Disattivare la cache del disco locale per il gruppo RAID, fondamentale per preservare l'integrità dei dati.


* La configurazione del LUN deve essere eseguita in base alle seguenti linee guida:
+
** Se le dimensioni del gruppo RAID superano le dimensioni LUN massime di 64TB GB, è necessario configurare più LUN di dimensioni uguali utilizzando tutto lo spazio di archiviazione disponibile all'interno del gruppo RAID.
** Se le dimensioni del gruppo RAID sono inferiori alle dimensioni LUN massime di 64TB GB, è necessario configurare un solo LUN utilizzando tutto lo spazio di archiviazione disponibile all'interno del gruppo RAID.






== Requisiti RAID software

Quando si implementa un cluster ONTAP Select sull'hypervisor, è possibile utilizzare la funzionalità software RAID fornita da ONTAP Select anziché un controller RAID hardware locale. Prima di implementare un cluster utilizzando il RAID software, è necessario conoscere diversi requisiti e restrizioni.



=== Requisiti generali

L'ambiente per una distribuzione RAID software deve soddisfare i seguenti requisiti fondamentali:

* VMware ESXi 7,0 GA (build 15843807) o versione successiva
* Licenza Premium ONTAP Select o superiore
* Solo unità SSD locali
* Separazione dei dischi di sistema dagli aggregati root e dati
* Nessun controller RAID hardware sull'host



NOTE: Se è presente un controller RAID hardware, consultare link:concept_stor_concepts_chars.html["Storage per immersioni profonde"] per ulteriori requisiti di configurazione.



=== Requisiti specifici di ESXi

* VMware ESXi 7,0 GA (build 15843807) o versione successiva
* VMware VMotion, ha e DRS non sono supportati
* Non è possibile utilizzare RAID software con un nodo aggiornato da ONTAP Select 9,4 o versione precedente. In questo caso, è necessario creare un nuovo nodo per l'implementazione del RAID software.




=== Requisiti specifici di KVM

Esistono anche requisiti specifici per la configurazione dei pacchetti software. Vedi il link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["preparazione del server Linux"] passaggio per maggiori informazioni.

Aspettative dei media per KVM:: I dispositivi di storage flash SSD utilizzati devono soddisfare i seguenti requisiti aggiuntivi:
+
--
* I dispositivi SSD devono segnalare in modo accurato e permanente se stessi all'host Linux mediante i seguenti metodi:
+
** # cat /sys/block/<device>/queue/rotational
+
Il valore riportato per questi comandi deve essere '0'.



* Si prevede che i dispositivi siano collegati a un HBA o, in alcuni casi, a un controller RAID configurato per funzionare in modalità JBOD. Quando si utilizza un controller RAID, la funzione del dispositivo deve essere passata attraverso l'host senza sovrapporre alcuna funzionalità RAID. Quando si utilizza un controller RAID in modalità JBOD, è necessario consultare la documentazione RAID o contattare il fornitore secondo necessità per assicurarsi che il dispositivo indichi la velocità di rotazione come '0'.
* Esistono due componenti di storage separati:
+
** Storage delle macchine virtuali
+
Si tratta di un pool LVM (pool di storage) contenente i dati di sistema utilizzati per ospitare la macchina virtuale ONTAP Select. Il pool LVM deve essere supportato da un dispositivo flash ad alta resistenza e può essere SAS, SATA o NVMe. Per migliorare le performance si consiglia un dispositivo NVMe.

** Dischi dati
+
Si tratta di un set di unità SSD SAS o SATA utilizzate per la gestione dei dati. I dispositivi SSD devono essere di livello Enterprise e resistenti. L'interfaccia NVMe non è supportata.



* Tutti i dispositivi devono essere formattati con 512BPS.


--




=== Configurazione del nodo ONTAP Select

Per separare i dischi di sistema dagli aggregati di dati e root, è necessario configurare ciascun nodo ONTAP Select e l'host dell'hypervisor come segue:

* Creare un pool di storage di sistema è necessario creare un pool di storage per i dati di sistema di ONTAP Select. È necessario collegare il pool di storage durante la configurazione del nodo ONTAP Select.
* Collegare i dischi fisici necessari l'host dell'hypervisor deve avere i dischi SSD necessari collegati e disponibili per l'utilizzo da parte della macchina virtuale ONTAP Select. Questi dischi conservano gli aggregati root e di dati. È necessario collegare i dischi di storage durante la configurazione del nodo ONTAP Select.




== Limitazioni della capacità dello storage

Nell'ambito della pianificazione di un'implementazione di ONTAP Select, è necessario conoscere le restrizioni relative all'utilizzo e all'allocazione dello storage.

Di seguito sono illustrate le principali restrizioni di storage. Per informazioni più dettagliate, consultare anche la link:https://mysupport.netapp.com/matrix/["Tool di matrice di interoperabilità"^].


TIP: ONTAP Select applica diverse restrizioni relative all'allocazione e all'utilizzo dello storage. Prima di implementare un cluster ONTAP Select o di acquistare una licenza, è necessario conoscere tali limitazioni. Vedere link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["Licenza"] per ulteriori informazioni.



=== Calcola la capacità dello storage raw

La capacità dello storage ONTAP Select corrisponde alla dimensione totale consentita dei dati virtuali e dei dischi root collegati alla macchina virtuale ONTAP Select. È necessario tenere in considerazione questo aspetto quando si assegna la capacità.



=== Capacità di storage minima per un cluster a nodo singolo

La dimensione minima del pool di storage allocato per il nodo in un cluster a nodo singolo è:

* Valutazione: 500 GB
* Produzione: 1.0 TB


L'allocazione minima per un'implementazione in produzione consiste di 1 TB per i dati dell'utente, più circa 266 GB utilizzati da vari processi interni di ONTAP Select, che viene considerato un overhead richiesto.



=== Capacità di storage minima per un cluster multi-nodo

La dimensione minima del pool di storage allocato per ciascun nodo in un cluster a più nodi è:

* Valutazione: 1.9 TB
* Produzione: 2.0 TB


L'allocazione minima per un'implementazione in produzione consiste di 2 TB per i dati utente, più circa 266 GB utilizzati da vari processi interni ONTAP Select, che viene considerato un overhead richiesto.

[NOTE]
====
Ogni nodo di una coppia ha deve avere la stessa capacità di storage.

Nel stimare la quantità di storage per una coppia ha, occorre valutare il mirroring di tutti gli aggregati (root e dati). Di conseguenza, ogni plesso dell'aggregato consuma altrettanta quantità di storage.

Ad esempio, quando viene creato un aggregato da 2TB TB, vengono allocate 2TB GB in due istanze plex (2TB GB per plex0 GB e 2TB GB per plex1 GB) o 4TB GB della quantità totale di storage concessa in licenza.

====


=== Capacità dello storage e più pool di storage

È possibile configurare ciascun nodo ONTAP Select in modo che utilizzi fino a 400 TB di storage quando si utilizzano storage direct-attached locale, VMware vSAN o storage array esterni. Tuttavia, un singolo pool di storage ha una dimensione massima di 64 TB quando si utilizzano storage direct-attached o array di storage esterni. Pertanto, se si prevede di utilizzare più di 64 TB di storage in queste situazioni, è necessario allocare più pool di storage come segue:

* Assegnare il pool di storage iniziale durante il processo di creazione del cluster
* Aumentare lo storage del nodo allocando uno o più pool di storage aggiuntivi



NOTE: Un buffer del 2% viene lasciato inutilizzato in ogni pool di storage e non richiede una licenza di capacità. Questo storage non viene utilizzato da ONTAP Select, a meno che non venga specificato un limite di capacità. Se viene specificato un limite massimo di capacità, la quantità di storage verrà utilizzata a meno che la quantità specificata non rientri nella zona di buffer del 2%. Il buffer è necessario per evitare errori occasionali che si verificano quando si tenta di allocare tutto lo spazio in un pool di storage.



=== Capacità dello storage e VMware vSAN

Quando si utilizza VMware vSAN, un datastore può superare i 64 TB. Tuttavia, è possibile allocare solo inizialmente fino a 64 TB quando si crea il cluster ONTAP Select. Una volta creato il cluster, è possibile allocare ulteriore storage dal datastore vSAN esistente. La capacità del datastore vSAN che può essere consumata da ONTAP Select si basa sul set di criteri di storage delle macchine virtuali.



=== Best practice

Si consiglia di prendere in considerazione i seguenti consigli relativi all'hardware di base dell'hypervisor:

* Tutti i dischi di un singolo aggregato ONTAP Select devono essere dello stesso tipo. Ad esempio, non si dovrebbero combinare dischi HDD e SSD nello stesso aggregato.




== Requisiti aggiuntivi per i dischi in base alla licenza della piattaforma

I dischi scelti sono limitati in base all'offerta di licenza della piattaforma.


NOTE: I requisiti dei dischi si applicano quando si utilizzano dischi e controller RAID locali, oltre che RAID software. Questi requisiti non si applicano allo storage esterno a cui si accede tramite la soluzione vNAS di ONTAP Select.

.Standard
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)


.Premium
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)
* Da 4 a 60 SSD interni


.Premium XL
* DA 8 A 60 HDD INTERNI (NL-SAS, SATA, SAS DA 10.000 RPM)
* Da 4 a 60 SSD interni
* Da 4 a 14 NVMe interni



NOTE: Il RAID software con dischi DAS locali è supportato con la licenza Premium (solo SSD) e la licenza Premium XL (SSD o NVMe).



== Dischi NVMe con RAID software

È possibile configurare il RAID software per l'utilizzo di unità SSD NVMe. L'ambiente deve soddisfare i seguenti requisiti:

* ONTAP Select con un'utilità di amministrazione Deploy supportata
* Offerta di licenza per piattaforma Premium XL o licenza di valutazione per 90 giorni
* VMware ESXi versione 6.7 o successiva
* Dispositivi NVMe conformi alla specifica 1.0 o successiva


È necessario configurare manualmente i dischi NVMe prima di utilizzarli. Vedere link:task_chk_nvme_configure.html["Configurare un host per utilizzare unità NVMe"] per ulteriori informazioni.
