---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 'Esistono diversi requisiti hardware e problemi di pianificazione da considerare relativi all"ambiente VMware.' 
---
= Considerazioni sull'hypervisor e sull'hardware di ONTAP Select VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono diversi requisiti hardware e problemi di pianificazione da considerare relativi all'ambiente VMware.



== Requisiti dell'hypervisor

Esistono diversi requisiti relativi all'hypervisor in cui viene eseguito ONTAP Select.


NOTE: Dovresti rivedere illink:reference_release_notes.html["Note di rilascio di ONTAP Select"] per eventuali ulteriori restrizioni o limitazioni note.



=== Licenze VMware

Per implementare un cluster ONTAP Select, l'organizzazione deve disporre di una licenza VMware vSphere valida per gli host hypervisor in cui viene eseguito ONTAP Select. Utilizzare le licenze appropriate per l'implementazione.



=== Compatibilità software

È possibile distribuire ONTAP Select sugli hypervisor KVM ed ESXi.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select supporta le seguenti versioni dell'hypervisor KVM:

* KVM su Red Hat Enterprise Linux 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6
* KVM su Rocky Linux 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6


--
.ESXi
--
ONTAP Select supporta le seguenti versioni dell'hypervisor ESXi:

* VMware ESXi 9.0
* VMware ESXi 8,0 U3
* VMware ESXi 8,0 U2
* VMware ESXi 8,0 U1 (build 21495797)
* VMware ESXi 8,0 GA (build 20513097)
* VMware ESXi 7.0 GA (build 15843807 o successiva) inclusi 7.0 U3C, U2 e U1



NOTE: NetApp supporta ONTAP Select sulle versioni identificate di ESXi, a condizione che anche VMware continui a supportare le stesse versioni.


NOTE: ESXi 6,5 GA e ESXi 6,7 GA hanno raggiunto lo stato di disponibilità. Se si dispone di cluster ONTAP Select con queste versioni, è necessario eseguire l'aggiornamento alle versioni supportate in base a. https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità (IMT)"^].

--
====


=== VMware vCenter e host ESXi standalone

Se un host hypervisor ESXi viene gestito da un server vCenter, è necessario registrare l'host nell'utility di amministrazione di deploy utilizzando le credenziali vCenter. Non è possibile registrare l'host come host standalone utilizzando le credenziali ESXi.



== Requisiti hardware fondamentali

L'host fisico dell'hypervisor in cui si implementa ONTAP Select deve soddisfare diversi requisiti hardware. È possibile scegliere qualsiasi piattaforma per l'host dell'hypervisor, purché soddisfi i requisiti hardware minimi. I seguenti vendor forniscono piattaforme hardware supportate: Cisco, Dell, HP, Fujitsu, Lenovo, E Supermicro.


NOTE: A partire da ONTAP Select 9.9.1, sono supportati solo i modelli di CPU basati su Intel Xeon Sandy Bridge o versioni successive.

Per ulteriori informazioni, fare riferimento alla https://mysupport.netapp.com/matrix["Strumento matrice di interoperabilità,finestra=_blank"] .



=== Requisiti hardware di base

Esistono diversi requisiti hardware comuni che si applicano a tutte le piattaforme, indipendentemente dal tipo di istanza del nodo o dall'offerta di licenza.

.Del processore
I microprocessori supportati includono i processori Intel Xeon per Server, vedere link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Processori Intel Xeon,window=_blank"] per maggiori informazioni.


NOTE: I processori AMD (Advanced Micro Devices) non sono supportati con ONTAP Select.

.Configurazione Ethernet
Sono supportate diverse configurazioni Ethernet in base alle dimensioni del cluster.

[cols="2,3,3"]
|===
| Dimensione del cluster | Requisiti minimi | Requisiti consigliati 


| Cluster a nodo singolo | 2 x 1 GbE | 2 x 10 GbE 


| Cluster a due nodi o SDS MetroCluster | 4 x 1 GbE o 1 x 10 GbE | 2 x 10 GbE 


| Cluster a quattro, sei o otto nodi | 2 x 10 GbE | 4 x 10 GbE o 2 x 25/40 GbE 
|===


=== Requisiti hardware aggiuntivi in base al tipo di istanza

Esistono diversi requisiti hardware aggiuntivi in base al tipo di istanza del nodo.

Fare riferimento a. link:concept_lic_platforms.html["Comprendere le offerte di licenza della piattaforma"] per ulteriori informazioni.

[cols="a1,a2,a2,a2"]
|===
| Dimensione del nodo | Core della CPU | Memoria | Offerta di licenza della piattaforma richiesta 


| Piccolo | Sei core fisici o più, di cui quattro riservati per ONTAP Select | 24 GB o più, con 16 GB riservati per ONTAP Select | Standard, premium o premium XL 


| Medio | Dieci core fisici o più, di cui otto riservati per ONTAP Select | 72 GB o superiore, con 64 GB riservati per ONTAP Select | Premium o premium XL 


| Grande | Diciotto core fisici o più, di cui sedici riservati per ONTAP Select | 136 GB o superiore, con 128 GB riservati per ONTAP Select | Premium XL 
|===

NOTE: Esistono requisiti aggiuntivi per i dischi in base alla licenza della piattaforma. Vedere link:reference_plan_ots_storage.html["Storage e RAID"] per ulteriori informazioni.
