---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, blogs, videos, imt, release notes, bugs, limitations, known issues 
summary: Sono disponibili ulteriori risorse a cui è possibile accedere per ottenere assistenza e ottenere ulteriori informazioni su ONTAP Select. 
---
= Dove trovare assistenza e ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sono disponibili ulteriori risorse a cui è possibile accedere per ottenere assistenza e ottenere ulteriori informazioni su ONTAP Select.



== Risorse di prodotto ONTAP Select

Le seguenti pagine dei prodotti includono collegamenti a un'ampia gamma di risorse ONTAP Select.

* https://www.netapp.com/data-management/ontap-select/documentation["Risorse NetApp ONTAP Select"^]
* https://www.netapp.com/us/products/data-management-software/ontap-select-sds.aspx["Pagina del prodotto NetApp ONTAP Select"^]




== Risorse di ONTAP 9

* https://docs.netapp.com/us-en/ontap/["Documentazione di ONTAP 9"^]
+
Fornisce la documentazione per ONTAP 9 (ad eccezione dei comandi CLI).

* https://docs.netapp.com/ontap-9/index.jsp["Centro documentazione di ONTAP 9"^]
+
Fornisce la documentazione per i comandi dell'interfaccia utente di ONTAP 9.





== Blog

È disponibile una raccolta di articoli del blog che trattano diversi aspetti di ONTAP Select.

* https://blog.netapp.com/tag/ontap-select/["Blog di NetApp ONTAP Select"^]




== Comunità

Puoi entrare in contatto con altri utenti per porre domande e contribuire alla community NetApp ONTAP Select.

* http://community.netapp.com/t5/forums/filteredbylabelpage/board-id/data-ontap-discussions/label-name/ontap%20select["Comunità NetApp: ONTAP Select"^]




== Tool di matrice di interoperabilità NetApp

Il tool Interoperability Matrix Tool contiene informazioni dettagliate sulla configurazione e sul supporto del prodotto.

* https://mysupport.netapp.com/matrix/["NetApp IMT"^]

