---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licenza Capacity Tiers si basa sulla capacità del disco sottostante gestita da ciascun nodo e non sulla capacità utilizzabile del nodo, della coppia HA o del cluster. Ogni licenza Capacity Tiers è assegnata a un singolo numero di serie di nodo per una capacità specifica e richiede un contratto di supporto allegato. 
---
= Considerazioni sul dimensionamento di una licenza ONTAP Select Capacity Tiers
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La licenza Capacity Tiers si basa sulla capacità del disco sottostante gestita da ciascun nodo ONTAP Select e non sulla capacità utilizzabile del nodo, della coppia HA o del cluster. Ogni licenza Capacity Tiers è assegnata a un singolo numero di serie di nodo per una capacità specifica e richiede un contratto di supporto allegato.

La capacità concessa in licenza per una licenza Capacity Tiers è espressa in TB interi, con un minimo di 1 TB. Calcoli la capacità concessa in licenza moltiplicando la quantità di spazio utilizzabile per il fattore di overhead. Il fattore di overhead stima la capacità di overhead del software ONTAP Select da prelevare dallo spazio utilizzabile e si applica per determinare la capacità ONTAP Select per unità NVMe, SSD, HDD o virtuali. Il fattore di overhead differisce tra cluster a nodo singolo e cluster multi-nodo (basati su coppia HA):

* Fattore di overhead per cluster a nodo singolo è 1.13
* Fattore di overhead per i cluster multi-nodo è 2,67


Devi calcolare la capacità concessa in licenza in base allo spazio utilizzabile per assicurarti di averne abbastanza per la tua implementazione. Ad esempio, vuoi 10 TB di capacità utilizzabile per una coppia HA (5 TB per nodo):

* Con una coppia HA, i dati vengono duplicati tra entrambi i nodi per ridondanza, quindi per 10 TB di dati utilizzabili in una coppia HA, ti servono 10 TB per nodo, nel caso in cui uno dei nodi vada offline.
* Il fattore 2,67 raddoppia la capacità di ciascun nodo e aggiunge la capacità di overhead (0,67) necessaria per il funzionamento di ONTAP Select.
* La capacità di licenza per nodo è di 14 TB (5 x 2,67 = 13,35). Per la coppia HA, ti servono due licenze da 14 TB per avere 10 TB di capacità utilizzabile.


[cols="25,30,45"]
|===
| Descrizione | Nodo singolo | Coppia HA 


| Spazio utilizzabile | 10 TB | 5 TB per nodo 10 TB per coppia HA 


| Spazio concesso in licenza | 12 TB (10 x 1,13 = 11,3, arrotondato al TB intero successivo) | Due licenze da 14 TB (5 x 2,67 = 13,35, arrotonda al TB completo successivo) 


| Spazio massimo utilizzabile per nodo *Nota*: lo spazio massimo gestito per nodo o coppia HA è 400 TB | 353 TB (400 / 1,13)  a| 
Per nodo in una coppia HA:

* 149 TB (400 / 2,67)


Per coppia HA in un cluster multi-nodo:

* Due nodi: 298 TB (2 x 149)
* Quattro nodi: 596 TB (4 x 149)
* Sei nodi: 894 TB (6 x 149)
* Otto nodi: 1.192 TB (8 x 149)
* Ten-node: 1.490 TB (10 x 149)
* Dodici nodi: 1,788 TB (12 x 149)


|===
.Cosa c'è dopo
link:task_lic_acquire_ct.html["Acquisisci una licenza Capacity Tier per ONTAP Select"]
