---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: La licenza Capacity Tiers si basa sulla capacità del disco sottostante gestita da ciascun nodo e non sulla capacità utilizzabile del nodo, della coppia HA o del cluster. Ogni licenza Capacity Tiers è assegnata a un singolo numero di serie di nodo per una capacità specifica e richiede un contratto di supporto allegato. 
---
= Determina la dimensione della licenza dei Capacity Pools per ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La capacità concessa in licenza per una Capacity Pool license è espressa in TB interi, con un minimo di 2 TB. Calcoli la capacità concessa in licenza moltiplicando la quantità di spazio utilizzabile per il fattore di overhead. Il fattore di overhead stima la capacità di overhead del software ONTAP Select da prelevare dallo spazio utilizzabile e si applica alla determinazione della capacità ONTAP Select per unità NVMe, SSD, HDD o virtuali. Il fattore di overhead varia tra cluster a nodo singolo e cluster multi-nodo (basati su coppia HA):

* Fattore di overhead per cluster a nodo singolo è 1.13
* Fattore di overhead per i cluster multi-nodo è 2,67


Devi calcolare la capacità concessa in licenza in base allo spazio utilizzabile per assicurarti di averne abbastanza per la tua implementazione. Ad esempio, vuoi 20 TB di capacità utilizzabile per una coppia HA (10 TB per nodo):

* Con una coppia HA, i dati vengono duplicati tra entrambi i nodi per ridondanza, quindi per 20 TB di dati utilizzabili in una coppia HA, devi avere 20 TB per nodo, nel caso in cui uno dei nodi vada offline.
* Il fattore 2,67 raddoppia la capacità di ciascun nodo e aggiunge la capacità di overhead (0,67) necessaria per il funzionamento di ONTAP Select.
* La capacità di licenza per nodo è di 27 TB (10 x 2,67 = 26,7). Per la coppia HA, ti servono due licenze da 27 TB per avere 20 TB di capacità utilizzabile.


[cols="25,30,45"]
|===
| Descrizione | Nodo singolo | coppia HA o mix di coppia HA e nodo singolo 


| Spazio utilizzabile | 20 TB | 10 TB per cluster a nodo singolo 20 TB per coppia HA 


| Spazio concesso in licenza | 23 TB (20 x 1,13 = 22,6, arrotonda al TB intero successivo) | 54 TB (20 x 2,67 = 53,4, arrotonda al TB intero successivo) 


| Spazio massimo utilizzabile per nodo *Nota*: lo spazio massimo gestito per nodo o coppia HA è 400 TB | 353 TB (400 / 1,13)  a| 
Per single-node in un cluster:

149 TB (400 / 2,67)

Per coppia HA in un cluster:

298 TB (2 x 149)

|===
.Cosa c'è dopo
link:task_lic_acquire_cp.html["Acquisisci una licenza Capacity Pools per ONTAP Select"]
