---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: 'È possibile utilizzare il plug-in Deploy vCenter tramite l"interfaccia utente Web di vSphere per implementare i cluster ONTAP Select.' 
---
= Implementare un cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare il plug-in Deploy vCenter tramite l'interfaccia utente Web di vSphere per implementare i cluster ONTAP Select.



== Prima di iniziare

Si consiglia di prepararsi a utilizzare il plug-in Deploy vCenter prima di implementare un cluster ONTAP Select.



=== Preparazione comune per cluster di tutte le dimensioni

È necessario eseguire diversi passaggi indipendentemente dalle dimensioni del cluster:

* Leggi la sezione _Guida introduttiva_ per acquisire familiarità con il plug-in Deploy vCenter.
* Assicurarsi che l'utility di amministrazione di ONTAP Select Deploy sia installata e in esecuzione.
* Installare il plug-in Deploy vCenter.
* Preparare l'host dell'hypervisor su cui verrà eseguito il cluster ONTAP Select.
* Acquisire i file di licenza storage richiesti per il nodo o i nodi nel cluster.
* Acquisire le credenziali per i seguenti account:
+
** Implementare l'account amministratore
** VCenter con accesso al plug-in


* Se necessario, installare il certificato di distribuzione SSL in Windows Certificate Manager come "autorità di certificazione principale attendibile".
* Assicurarsi che l'utility di implementazione disponga dell'accesso di rete alla porta 443 del server vCenter.




=== Preparazione aggiuntiva per un cluster a più nodi

Oltre alla preparazione comune, è necessario avere familiarità con il tool di verifica della rete di implementazione prima di implementare un cluster a più nodi.



== Aggiunta di un host hypervisor

È possibile aggiungere gli host degli hypervisor all'utilità di implementazione in cui verranno eseguiti i nodi ONTAP Select prima di implementare un cluster. Se necessario, è possibile aggiungere gli host come parte della finestra di dialogo di creazione del cluster.

.Prima di iniziare
Si consiglia di esaminare la preparazione per l'implementazione di un cluster ONTAP Select.

.A proposito di questa attività
È possibile aggiungere uno o più host in base alle dimensioni del cluster.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Nella barra degli strumenti, fare clic su *Menu*, quindi su *Global Inventory Lists*.
. Nel riquadro a sinistra, fare clic su *ONTAP Select Deploy*, quindi fare clic sulla scheda *Hosts*.
. Fare clic su *Add* (Aggiungi) a destra.
. Fornire il nome host o l'indirizzo IP dell'host, quindi fare clic su *Aggiungi* o *Aggiungi ed esci*.




== Crea un cluster a nodo singolo

È possibile utilizzare il plug-in VMware vCenter tramite il client Web vSphere per implementare un cluster ONTAP Select costituito da un singolo nodo.

.Prima di iniziare
Si consiglia di esaminare la preparazione per l'implementazione di un cluster ONTAP Select e l'aggiunta di un host hypervisor. È possibile aggiungere l'host su cui verrà eseguito il nodo ONTAP Select prima di creare il cluster o come parte della creazione del cluster a nodo singolo.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Fare clic su *Menu* nella parte superiore, quindi su *Global Inventory Lists*.
. Fare clic su *ONTAP Select Clusters* nel riquadro a sinistra, quindi fare clic su *New ONTAP Select*.
+
Se il certificato SSL non è stato accettato in precedenza, fare clic sul collegamento IP nel messaggio di avviso e accettare il certificato. Tornare quindi alla pagina vCenter e fare clic sul collegamento nel messaggio di avviso per ricaricare la pagina.

. Nella pagina *New ONTAP Select* (nuovo cluster), inserire i dettagli del cluster e fare clic su *Done* (fine).
. Nella sezione *Node Setup*, fornire la configurazione e selezionare una licenza.
+
È possibile modificare il nome del nodo predefinito e caricare una nuova licenza, se necessario.

. Nella sezione *Hypervisor e Network*, selezionare il tipo di istanza, l'host e le reti.
+
Se necessario, è possibile aggiungere un host. La licenza per il nodo deve soddisfare o superare il tipo di istanza.

. Nella sezione *Storage*, selezionare la capacità dello storage e un pool di storage.
+
Se si utilizza una licenza Premium, è possibile abilitare il RAID software.

. Fare clic su *Done* (fine) ed esaminare la configurazione del cluster.
+
È possibile modificare la configurazione facendo clic su Edit (Modifica) in ciascuna sezione.

. Fare clic su *Avanti*.
. Inserire la password dell'amministratore di ONTAP e fare clic su *Crea cluster* per avviare il processo di creazione del cluster, quindi fare clic su *OK* nella finestra a comparsa di conferma.
+
La creazione del cluster può richiedere fino a 30 minuti.

. Aggiornare la pagina e selezionare il nuovo cluster, quindi fare clic su *Summary* (Riepilogo) e *Details* (Dettagli) per monitorare il processo di creazione del cluster a più fasi.
+

TIP: Se l'operazione di creazione del cluster viene avviata ma non viene completata, la password amministrativa ONTAP definita non viene registrata. In questo caso, è possibile accedere all'interfaccia di gestione del cluster ONTAP Select utilizzando la password `changeme123` con `admin` account.



.Al termine
* Verificare che la funzione ONTAP Select AutoSupport sia attivata.
* Eseguire il backup dei dati di configurazione di implementazione di ONTAP Select.




== Creare un cluster multi-nodo

È possibile utilizzare il plug-in VMware vCenter tramite il client Web vSphere per implementare un cluster ONTAP Select composto da più nodi.

.Prima di iniziare
Si consiglia di esaminare la preparazione per l'implementazione di un cluster ONTAP Select e l'aggiunta di un host hypervisor. È possibile aggiungere gli host su cui verranno eseguiti i nodi ONTAP Select prima di creare il cluster o come parte della creazione del cluster a più nodi.

.A proposito di questa attività
Un cluster multi-nodo ONTAP Select è costituito da un numero pari di nodi. I nodi sono sempre Uniti come coppie ha.

.Fasi
. Accedere al server vCenter tramite vSphere HTML5 utilizzando un browser.
. Fare clic su *Menu* nella parte superiore, quindi su *Global Inventory Lists*.
. Fare clic su *ONTAP Select Clusters* nel riquadro a sinistra, quindi fare clic su *New ONTAP Select*
+
Se il certificato SSL non è stato accettato in precedenza, fare clic sul collegamento IP nel messaggio di avviso e accettare il certificato. Tornare quindi alla pagina vCenter e fare clic sul collegamento nel messaggio di avviso per ricaricare la pagina.

. Nella pagina *New ONTAP Select* (nuovo cluster), inserire i dettagli del cluster e fare clic su *Done* (fine).
+
A meno che non si disponga di un motivo per impostare la dimensione MTU del cluster, è necessario accettare il valore predefinito e consentire l'implementazione, apportare eventuali modifiche in base alle necessità.

. Nella sezione *Node Setup*, fornire la configurazione e selezionare le licenze per i due nodi della coppia ha.
+
È possibile modificare i nomi dei nodi predefiniti e caricare nuove licenze, se necessario.

. Nella sezione *Hypervisor e Network*, selezionare il tipo di istanza, l'host e le reti per ciascun nodo.
+
Se necessario, è possibile aggiungere un host. Selezionare le tre reti. La rete interna non può essere uguale alla rete di gestione o alla rete dati. Le licenze per i nodi devono soddisfare o superare il tipo di istanza.

. Nella sezione *Storage*, selezionare la capacità dello storage e un pool di storage.
+
Se si utilizza una licenza Premium, è possibile abilitare il RAID software.

. Se il cluster ha quattro o più nodi, è necessario configurare i nodi nelle coppie ha aggiuntive seguendo le stesse procedure utilizzate per la prima coppia ha.
. Fare clic su *Done* (fine) ed esaminare la configurazione del cluster.
+
È possibile modificare la configurazione facendo clic su *Edit* (Modifica) in ciascuna sezione.

. Facoltativamente, eseguire il controllo della connettività di rete per verificare la connettività tra i nodi sulla rete cluster interna.
. Fare clic su *Avanti*.
. Inserire la password dell'amministratore di ONTAP e fare clic su *Crea cluster* per avviare il processo di creazione del cluster, quindi fare clic su *OK* nella finestra a comparsa di conferma.
+
La creazione del cluster può richiedere fino a 30 minuti.

. Aggiornare la pagina e selezionare il nuovo cluster, quindi fare clic su *Summary* (Riepilogo) e *Details* (Dettagli) per monitorare il processo di creazione del cluster a più fasi.
+

TIP: Se l'operazione di creazione del cluster viene avviata ma non viene completata, la password amministrativa ONTAP definita non viene registrata. In questo caso, è possibile accedere all'interfaccia di gestione del cluster ONTAP Select utilizzando la password `changeme123` con `admin` account.



.Al termine
* Verificare che la funzione ONTAP Select AutoSupport sia attivata.
* Eseguire il backup dei dati di configurazione di implementazione di ONTAP Select.

