---
sidebar: sidebar 
permalink: task_vpi_adm_network.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking 
summary: È possibile esplorare e visualizzare diversi aspetti della rete. 
---
= Verificare la connettività di rete
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile esplorare e visualizzare diversi aspetti della rete.



== Verificare la connettività di rete

È possibile verificare la connettività di rete tra due o più nodi ONTAP Select sulla rete cluster interna. In genere, è necessario eseguire questo test prima di implementare un cluster a più nodi per rilevare problemi che potrebbero causare un errore dell'operazione. È inoltre possibile eseguire il test di connettività dopo l'implementazione e la connessione in linea di un cluster.

.A proposito di questa attività
Ogni volta che si avvia il test, viene creato un nuovo processo in background e viene assegnato un identificatore di esecuzione univoco. È possibile attivare una sola seriografia alla volta.

Il test viene eseguito sempre in modalità rapida, che esegue un test di base senza interruzioni. Viene eseguito un TEST PING, insieme a un test delle dimensioni MTU della rete e di vSwitch.

.Fasi
. Fare clic su *ONTAP Select Deploy* nel riquadro *elenchi di inventario globali*.
. Fare clic sulla scheda *Amministrazione*.
. Espandere l'opzione *Network* e fare clic su *Connectivity Checker*.
. Fare clic su *Run New* (Esegui nuovo) per avviare il test.
. Facoltativamente, fare clic su *Filtering* e creare un filtro per limitare i dettagli del test visualizzati.




== Visualizzare lo stato del servizio mediatore

Ogni cluster a due nodi ONTAP Select viene monitorato dal servizio mediatore, che assiste nella gestione della funzionalità ha condivisa dai nodi. È possibile visualizzare lo stato del servizio mediatore per ciascuno dei cluster a due nodi definiti nell'utilità di amministrazione della distribuzione.

.A proposito di questa attività
È possibile visualizzare la configurazione di ciascun mediatore, tra cui:

* Stato corrente
* Due nodi ONTAP Select
* Destinazione iSCSI in cui vengono memorizzate le informazioni di controllo ha


.Fasi
. Fare clic su *ONTAP Select Deploy* nel riquadro *elenchi di inventario globali*.
. Fare clic sulla scheda *Amministrazione*.
. Espandere l'opzione *Mediator* e fare clic su *Status*.
. Facoltativamente, fare clic su *Filtering* e creare un filtro per personalizzare la visualizzazione dei cluster a due nodi monitorati dal servizio di mediatore.

