---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 'Se l"utilità di implementazione di ONTAP Select non riesce o non è disponibile per qualche motivo, si perde la capacità di amministrare i nodi e i cluster ONTAP Select. Inoltre, tutti i cluster a due nodi perdono la funzionalità ha perché il servizio mediatore incluso con l"implementazione non è disponibile. Se si verifica un errore irreversibile, è necessario ripristinare l"istanza dell"utilità di implementazione per ripristinare la funzionalità amministrativa e ha.' 
---
= Ripristinare l'utility ONTAP Select Deploy per un cluster a due nodi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se l'utilità di implementazione di ONTAP Select non riesce o non è disponibile per qualche motivo, si perde la capacità di amministrare i nodi e i cluster ONTAP Select. Inoltre, tutti i cluster a due nodi perdono la funzionalità ha perché il servizio mediatore incluso con l'implementazione non è disponibile. Se si verifica un errore irreversibile, è necessario ripristinare l'istanza dell'utilità di implementazione per ripristinare la funzionalità amministrativa e ha.



== Prepararsi a ripristinare l'utilità Deploy

Per garantire il successo dell'operazione, è necessario prepararsi prima di tentare di ripristinare un'istanza dell'utilità Deploy.  È necessario avere familiarità con diverse procedure amministrative e disporre delle informazioni richieste.

.Fasi
. Verificare di poter installare una nuova istanza dell'utilità ONTAP Select Deploy nel proprio ambiente hypervisor.
+
link:task_install_deploy.html["Scopri come installare l'utilità ONTAP Select Deploy"]

. Verificare di poter accedere al cluster ONTAP Select e alla shell del cluster ONTAP (CLI).
. Determinare se si dispone di un backup dei dati di configurazione dall'istanza dell'utilità Deploy non riuscita che contiene il cluster a due nodi ONTAP Select . È possibile che il backup non contenga il cluster.
. Verificare che sia possibile ripristinare un backup dei dati di configurazione di Deploy, a seconda della procedura di ripristino utilizzata.
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["Scopri come ripristinare i dati di configurazione di distribuzione sulla nuova macchina virtuale"]

. Hai l'indirizzo IP della macchina virtuale dell'utilità Deploy originale che ha generato un errore.
. Determinare se si utilizza la licenza Capacity Pools o Capacity Tiers. Se si utilizza la licenza Capacity Pools, è necessario reinstallare ciascuna licenza Capacity Pool dopo aver ripristinato o ripristinato l'istanza di Deploy.
. Decidere quale procedura utilizzare per ripristinare un'istanza dell'utilità ONTAP Select Deploy. La decisione dipende dalla disponibilità o meno di un backup dei dati di configurazione dell'utility Deploy originale non riuscita, contenente il cluster a due nodi ONTAP Select .
+
[cols="35,65"]
|===
| Si dispone di un backup di implementazione contenente il cluster a due nodi? | Utilizzare la procedura di recupero... 


| Sì | <<restore-deploy-backup,Ripristinare un'istanza dell'utilità di distribuzione utilizzando un backup di configurazione>> 


| No | <<restore-and-recover-deploy,Riconfigurare e ripristinare un'istanza dell'utilità di distribuzione>> 
|===




== Ripristinare un'istanza dell'utilità di distribuzione utilizzando un backup di configurazione

Se si dispone di un backup dell'istanza dell'utilità di implementazione non riuscita contenente il cluster a due nodi, è possibile ripristinare i dati di configurazione nella nuova istanza della macchina virtuale di implementazione. A questo punto, è necessario completare il ripristino eseguendo una configurazione aggiuntiva dei due nodi nel cluster ONTAP Select.

.Prima di iniziare
Eseguire il backup dei dati di configurazione dalla macchina virtuale Deploy originale non riuscita che contiene il cluster a due nodi. È necessario poter accedere alla CLI ONTAP del cluster a due nodi e conoscere i nomi ONTAP dei due nodi.

.A proposito di questa attività
Poiché il backup della configurazione ripristinato contiene il cluster a due nodi, le destinazioni iSCSI del mediatore e le caselle postali vengono ricreate nella nuova macchina virtuale dell'utility di implementazione.

.Fasi
. Preparare una nuova istanza dell'utilità di implementazione di ONTAP Select:
+
.. Installare una nuova macchina virtuale dell'utility di implementazione.
.. Ripristinare la configurazione di implementazione da un backup precedente alla nuova macchina virtuale.
+
Fare riferimento alle attività correlate per informazioni più dettagliate sulle procedure di installazione e ripristino.



. Accedere all'interfaccia della riga di comando ONTAP del cluster a due nodi ONTAP Select.
. Accedere alla modalità avanzata dei privilegi:
+
[source, cli]
----
set adv
----
. Se l'indirizzo IP della nuova macchina virtuale Deploy è diverso da quello della macchina virtuale Deploy originale, rimuovere le vecchie destinazioni iSCSI del mediatore e aggiungere nuove destinazioni:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
Il `<ip_address>` Il parametro è l'indirizzo IP della nuova macchina virtuale di implementazione.

+
Questi comandi consentono ai nodi ONTAP Select di rilevare i dischi della mailbox sulla nuova macchina virtuale dell'utility di implementazione.

. Determinare i nomi dei dischi del mediatore:
+
[source, cli]
----
disk show -container-type mediator
----
. Assegnare i dischi della mailbox ai due nodi:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Verificare che il failover dello storage sia attivato:
+
[source, cli]
----
storage failover show
----


.Al termine
Se si utilizza la licenza Capacity Pools, reinstallare ogni licenza Capacity Pool.  Vederelink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Reinstallare una licenza di Capacity Pool"] per ulteriori dettagli.



== Riconfigurare e ripristinare un'istanza dell'utilità di distribuzione

Se non si dispone di un backup dell'istanza dell'utilità Deploy non riuscita contenente il cluster a due nodi, configurare la destinazione iSCSI del mediatore e la cassetta postale nella nuova macchina virtuale Deploy.  È quindi possibile completare il ripristino eseguendo un'ulteriore configurazione dei due nodi nel cluster ONTAP Select .

.Prima di iniziare
Verificare di disporre del nome della destinazione del mediatore per la nuova istanza dell'utilità di distribuzione. È necessario poter accedere alla CLI ONTAP del cluster a due nodi e conoscere i nomi ONTAP dei due nodi.

.A proposito di questa attività
È possibile ripristinare un backup della configurazione sulla nuova macchina virtuale di implementazione anche se non contiene il cluster a due nodi. Poiché il cluster a due nodi non viene ricreato con il ripristino, è necessario aggiungere manualmente la destinazione iSCSI del mediatore e la mailbox alla nuova istanza dell'utilità di implementazione attraverso la pagina Web della documentazione online di ONTAP Select nella distribuzione. È necessario essere in grado di accedere al cluster a due nodi e conoscere i nomi ONTAP dei due nodi.


NOTE: L'obiettivo della procedura di ripristino è ripristinare il cluster a due nodi in uno stato integro, in cui è possibile eseguire normali operazioni di Takeover e giveback di ha.

.Fasi
. Preparare una nuova istanza dell'utilità di implementazione di ONTAP Select:
+
.. Installare una nuova macchina virtuale dell'utility di implementazione.
.. Se si desidera, ripristinare la configurazione di implementazione da un backup precedente alla nuova macchina virtuale.
+
Se si ripristina un backup precedente, la nuova istanza di implementazione non conterrà il cluster a due nodi. Per informazioni più dettagliate sulle procedure di installazione e ripristino, consultare la sezione relativa alle informazioni correlate.



. Accedere all'interfaccia della riga di comando ONTAP del cluster a due nodi ONTAP Select.
. Accedere alla modalità avanzata con privilegi:
+
[source, cli]
----
set adv
----
. Ottenere il nome di destinazione iSCSI del mediatore:
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. Accedere alla pagina Web della documentazione online sulla nuova macchina virtuale dell'utility di implementazione e accedere utilizzando l'account admin:
+
`\http://<ip_address>/api/ui`

+
È necessario utilizzare l'indirizzo IP della macchina virtuale di implementazione.

. Selezionare *Mediatore* e poi *GET /mediators*.
. Seleziona *Provalo!* per visualizzare un elenco dei mediatori gestiti da Deploy.
+
Annotare l'ID dell'istanza del mediatore desiderata.

. Selezionare *Mediatore* e poi *POST*.
. Fornire il valore per mediator_ID.
. Seleziona il *Modello* accanto a `iscsi_target` e completa il valore del nome.
+
Utilizzare il nome di destinazione per il parametro iqn_NAME.

. Selezionare *Provalo!* per creare la destinazione iSCSI del mediatore.
+
Se la richiesta ha esito positivo, si riceverà il codice di stato HTTP 200.

. Se l'indirizzo IP della nuova macchina virtuale di implementazione è diverso da quello della macchina virtuale di implementazione originale, è necessario utilizzare la CLI ONTAP per rimuovere le destinazioni iSCSI del mediatore precedente e aggiungere nuove destinazioni:
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
Il `<ip_address>` Il parametro è l'indirizzo IP della nuova macchina virtuale di implementazione.

+
Questi comandi consentono ai nodi ONTAP Select di rilevare i dischi della mailbox sulla nuova macchina virtuale dell'utility di implementazione.

. Determinare i nomi dei dischi del mediatore:
+
[source, cli]
----
disk show -container-type mediator
----
. Assegnare i dischi della mailbox ai due nodi:
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. Verificare che il failover dello storage sia attivato:
+
[source, cli]
----
storage failover show
----


.Al termine
Se si utilizza la licenza Capacity Pools, reinstallare ogni licenza Capacity Pool.  Vederelink:task_adm_licenses.html#reinstall-a-capacity-pool-license["Reinstallare una licenza di Capacity Pool"] per ulteriori dettagli.
