---
sidebar: sidebar 
permalink: task_vpi_manually_remove.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter, remove, removing, manually removing 
summary: È possibile rimuovere manualmente il plug-in di implementazione dal server vCenter. 
---
= Rimozione manuale del plug-in di implementazione da vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile rimuovere manualmente il plug-in di implementazione dal server vCenter.



== Prima di iniziare

Si consiglia di iniziare sempre rimuovendo il plug-in utilizzando VMware Managed Object browser (MOB), quindi rimuovendo il plug-in dalle directory vSphere all'interno del server vCenter.

Esistono diversi casi in cui è necessario rimuovere manualmente il plug-in:

* Il plug-in è stato rimosso utilizzando l'interfaccia utente nativa dell'utility di distribuzione, ma non è stato possibile riavviare il server vCenter.
* L'utilità di implementazione è stata dismessa senza rimuovere il plug-in.




== Utilizzare VMware MOB per rimuovere il plug-in

MOB è un'applicazione VMware che consente di visualizzare e gestire gli oggetti su un server VMware vCenter. È possibile utilizzare MOB per rimuovere il plug-in Deploy vCenter.

.Fasi
. Accedere al MOB dal server vCenter utilizzando un browser ed effettuare l'accesso:
+
`\https://<FQDN_or_IP-address>/mob`

. Fare clic su *content*, quindi su *ExtensionManager*.
. Verificare che l'interno da rimuovere sia presente in base al nome completo:
+
`com.netapp.selectdeploy`

. Fare clic su *UnregisterExtension*.
. Digitare il nome dell'interno e fare clic su *InvokeMethod*.


.Risultato
Il plug-in viene rimosso dall'elenco delle estensioni.



== Rimuovere il plug-in dalla cartella dell'interfaccia utente di vSphere

Esaminare la directory dell'interfaccia utente di vSphere sul server vCenter e rimuovere il plug-in di implementazione, se trovato.

.Prima di iniziare
È necessario disporre della password per l'account root sul server vCenter. Rimuovere il plug-in utilizzando vSphere MOB.

.Fasi
. Utilizzare SSH per accedere al server vCenter e accedere:
+
`ssh root@<FQDN_or_IP-address>`

. Digitare *shell* e premere *Invio* per avviare la shell Bash.
. Passare a. `vsphere-client-serenity` Directory per il servizio vSphere-UI:
+
`cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`

. Determinare se sono presenti directory del modulo `com.netapp.selectdeploy` che devono essere rimossi:
+
`ls -al`

. Arrestare il client Web vSphere-UI HTML5:
+
`service-control --stop vsphere-ui`

. Rimuovere la directory contenente le estensioni dell'interfaccia utente:
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. Riavviare il client Web vSphere-UI HTML5:
+
`service-control --start vsphere-ui`



.Al termine
Il riavvio e la disponibilità del plug-in di implementazione possono richiedere alcuni minuti.



== Rimuovere il plug-in dalla cartella del client vSphere

Esaminare la directory vSphere Client nel server vCenter e rimuovere il plug-in di implementazione, se presente. Sebbene il plug-in di implementazione non utilizzi Flash, è consigliabile esaminare questa directory come parte della procedura di rimozione del plug-in.

.Prima di iniziare
È necessario disporre della password per l'account root sul server vCenter. Rimuovere il plug-in utilizzando vSphere MOB e rimuovere il plug-in dalla directory dell'interfaccia utente di vSphere.

.Fasi
. Utilizzare SSH per accedere al server vCenter e accedere:
+
`ssh root@<FQDN_or_IP-address>`

. Digitare *shell* e premere *Invio* per avviare la shell Bash.
. Passare a. `vsphere-client-serenity` Directory per il servizio vSphere-Client:
+
`cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`

. Determinare se sono presenti directory del modulo `com.netapp.selectdeploy` che devono essere rimossi:
+
`ls -al`

. Arrestare il client Web vSphere-UI HTML5:
+
`service-control --stop vsphere-client`

. Rimuovere la directory contenente le estensioni del client:
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. Riavviare il client Web vSphere-UI HTML5:
+
`service-control --start vsphere-client`



.Al termine
Il riavvio e la disponibilità del plug-in di implementazione possono richiedere alcuni minuti.
