---
sidebar: sidebar 
permalink: task_vpi_adm_clusters.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, clusters 
summary: Per amministrare un cluster ONTAP Select è possibile eseguire diverse attività correlate. 
---
= Cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per amministrare un cluster ONTAP Select è possibile eseguire diverse attività correlate.



== Spostare un cluster ONTAP Select negli stati offline e online

Dopo aver creato un cluster, è possibile modificarne lo stato in offline o online in base alle necessità.

.Fasi
. Fare clic su *ONTAP Select Clusters* nel riquadro *elenchi di inventario globali*.
. Fare clic con il pulsante destro del mouse sul cluster desiderato per visualizzare le azioni disponibili.
. Fare clic su *take Offline* o *Bring Online*, a seconda dei casi, e fare clic su *Yes* per confermare la richiesta.




== Eliminare un cluster ONTAP Select

È possibile eliminare un cluster ONTAP Select quando non è più necessario.

.Prima di iniziare
Il cluster deve essere in stato offline.

.Fasi
. Fare clic su *ONTAP Select Clusters* nel riquadro *elenchi di inventario globali*.
. Fare clic con il pulsante destro del mouse sul cluster desiderato per visualizzare le azioni disponibili.
. Fare clic su *Delete Cluster* (Elimina cluster) e fare clic su *Yes* (Sì) per confermare la richiesta.
+
Se l'opzione di eliminazione non è disponibile, il cluster non si trova in uno stato offline.


