---
sidebar: sidebar 
permalink: task_cli_upgrade_esxi65.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 6.5 
summary: 'Se si esegue ONTAP Select su VMware ESXi, è possibile aggiornare il software ESXi da una versione precedente supportata a ESXi 7,0 o versione successiva. Prima di eseguire l"aggiornamento, è necessario comprendere il processo e selezionare la procedura di aggiornamento appropriata.' 
---
= Aggiornare ONTAP Select VMware ESXi alla versione 7,0 o successiva
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si esegue ONTAP Select su VMware ESXi, è possibile aggiornare il software ESXi da una versione precedente supportata a ESXi 7,0 o versione successiva. Prima di eseguire l'aggiornamento, è necessario comprendere il processo e selezionare la procedura di aggiornamento appropriata.



== Prima di iniziare

Prima di aggiornare il software ESXi sugli hypervisor che ospitano un cluster ONTAP Select, è necessario preparare e selezionare la procedura di aggiornamento appropriata per il proprio ambiente.


CAUTION: Se si sceglie di eseguire l'aggiornamento a VMware ESXi 6.5, è necessario eseguire l'aggiornamento a ESXi U2 (build 8294253) o superiore. L'utilizzo di ESXi 6.5 U1 può esporre l'utente a un guasto di una macchina virtuale dovuto a un bug noto di VMware.



=== Acquisire familiarità con l'aggiornamento di VMware ESXi

L'aggiornamento del software ESXi è un processo descritto e supportato da VMware. Il processo di aggiornamento dell'hypervisor fa parte della procedura di aggiornamento più estesa quando si utilizza ONTAP Select. Per ulteriori informazioni, consultare la documentazione VMware.



=== Selezionare una procedura di aggiornamento

Sono disponibili diverse procedure di aggiornamento. Selezionare la procedura appropriata in base ai seguenti criteri:

* Le dimensioni del cluster ONTAP Select sono supportate sia cluster a nodo singolo che cluster a nodo multiplo.
* L'utilizzo dell'aggiornamento ONTAP Select Deploy è possibile sia con che senza l'utility di implementazione.



TIP: Selezionare una procedura di aggiornamento che utilizzi l'utility di amministrazione di deploy.

L'esecuzione di un aggiornamento ESXi con l'utility di amministrazione di Deploy è l'opzione più generale e resiliente. Tuttavia, potrebbero esserci delle istanze quando la distribuzione non è disponibile o non può essere utilizzata. Ad esempio, l'aggiornamento a ESXi 7,0 non è supportato dalle versioni precedenti di ONTAP Select e dall'utilità di amministrazione di distribuzione.

Se si utilizzano queste versioni precedenti e si tenta di eseguire un aggiornamento, è possibile lasciare la macchina virtuale ONTAP Select in uno stato in cui non è possibile avviarla. In questo caso, è necessario selezionare una procedura di aggiornamento che non utilizza la distribuzione. Fare riferimento a. link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] per ulteriori informazioni.



=== Aggiornare l'utilità di amministrazione distribuzione

Prima di eseguire una procedura di aggiornamento utilizzando l'utility di distribuzione, potrebbe essere necessario aggiornare l'istanza di distribuzione. In generale, è necessario eseguire l'aggiornamento alla versione più recente di Deploy. L'utility di distribuzione deve supportare la versione di ONTAP Select in uso. Per ulteriori informazioni, consultare le note di rilascio di ONTAP Select.



=== Al termine della procedura di aggiornamento

Se si seleziona una procedura di aggiornamento che utilizza l'utility di distribuzione, è necessario eseguire un'operazione di refresh del cluster utilizzando Deploy dopo che tutti i nodi sono stati aggiornati. Per ulteriori informazioni, vedere aggiornamento della configurazione del cluster di implementazione.



== Aggiorna un cluster a nodo singolo utilizzando l'implementazione

È possibile utilizzare l'utility di amministrazione di deploy come parte della procedura per aggiornare l'hypervisor VMware ESXi che ospita un cluster a nodo singolo ONTAP Select.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore.
. Spostare il nodo nello stato offline.
+
Esempio
`node stop --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. Aggiornare l'host dell'hypervisor in cui ONTAP Select è in esecuzione a ESXi 7,0 o versioni successive utilizzando la procedura fornita da VMware.
. Spostare il nodo nello stato online.
+
Esempio
`node start --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. Una volta attivato il nodo, verificare che il cluster funzioni correttamente.
+
Esempio

+
....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....


.Al termine
È necessario eseguire un'operazione di refresh del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster multi-nodo utilizzando l'implementazione

È possibile utilizzare l'utility di amministrazione di Deploy come parte della procedura per aggiornare gli hypervisor VMware ESXi che ospitano un cluster multi-nodo ONTAP Select.

.A proposito di questa attività
È necessario eseguire questa procedura di aggiornamento per ciascuno dei nodi del cluster, un nodo alla volta. Se il cluster contiene quattro o più nodi, è necessario aggiornare i nodi di ciascuna coppia ha in sequenza prima di passare alla coppia ha successiva.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore.
. Spostare il nodo nello stato offline.
+
Esempio
`node stop --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. Aggiornare l'host dell'hypervisor in cui ONTAP Select è in esecuzione a ESXi 7,0 o versioni successive utilizzando la procedura fornita da VMware.
+
Per ulteriori informazioni, consultare la sezione preparazione all'aggiornamento di VMware ESXi.

. Spostare il nodo nello stato online.
+
Esempio
`node start --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. Una volta attivato il nodo, verificare che il failover dello storage sia attivato e che il cluster funzioni correttamente.
+
Esempio

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.Al termine
È necessario eseguire la procedura di aggiornamento per ciascun host utilizzato nel cluster ONTAP Select. Una volta aggiornati tutti gli host ESXi, è necessario eseguire un'operazione di aggiornamento del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster a nodo singolo senza eseguire l'implementazione

È possibile aggiornare l'hypervisor VMware ESXi che ospita un cluster a nodo singolo ONTAP Select senza utilizzare l'utility di amministrazione Deploy.

.Fasi
. Accedere all'interfaccia della riga di comando di ONTAP e arrestare il nodo.
. Utilizzando VMware vSphere, verificare che la macchina virtuale ONTAP Select sia spenta.
. Aggiornare l'host dell'hypervisor in cui ONTAP Select è in esecuzione a ESXi 7,0 o versioni successive utilizzando la procedura fornita da VMware.
+
Per ulteriori informazioni, consultare la sezione preparazione all'aggiornamento di VMware ESXi.

. Utilizzando VMware vSphere, accedere a vCenter ed effettuare le seguenti operazioni:
+
.. Aggiungere un disco floppy alla macchina virtuale ONTAP Select.
.. Accendere la macchina virtuale ONTAP Select.
.. Accedere all'interfaccia utente di ONTAP utilizzando SSH con l'account amministratore.


. Una volta attivato il nodo, verificare che il cluster funzioni correttamente.
+
Esempio



....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....
.Al termine
È necessario eseguire un'operazione di refresh del cluster utilizzando l'utility di amministrazione di deploy.



== Aggiorna un cluster multi-nodo senza eseguire l'implementazione

È possibile aggiornare gli hypervisor VMware ESXi che ospitano un cluster multi-nodo ONTAP Select senza utilizzare l'utility di amministrazione Deploy.

.A proposito di questa attività
È necessario eseguire questa procedura di aggiornamento per ciascuno dei nodi del cluster, un nodo alla volta. Se il cluster contiene quattro o più nodi, è necessario aggiornare i nodi di ciascuna coppia ha in sequenza prima di passare alla coppia ha successiva.

.Fasi
. Accedere all'interfaccia della riga di comando di ONTAP e arrestare il nodo.
. Utilizzando VMware vSphere, verificare che la macchina virtuale ONTAP Select sia spenta.
. Aggiornare l'host dell'hypervisor in cui ONTAP Select è in esecuzione a ESXi 7,0 o versioni successive utilizzando la procedura fornita da VMware.
. Utilizzando VMware vSphere, accedere a vCenter ed effettuare le seguenti operazioni:
+
.. Aggiungere un disco floppy alla macchina virtuale ONTAP Select.
.. Accendere la macchina virtuale ONTAP Select.
.. Accedere all'interfaccia utente di ONTAP utilizzando SSH con l'account amministratore.


. Una volta attivato il nodo, verificare che il failover dello storage sia attivato e che il cluster funzioni correttamente.
+
Esempio

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.Al termine
È necessario eseguire la procedura di aggiornamento per ciascun host utilizzato nel cluster ONTAP Select.
