---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partire da ONTAP Select 9.15.1 è possibile aumentare le dimensioni di un cluster esistente da sei a otto nodi e ridurre le dimensioni del cluster da otto a sei nodi. 
---
= Espansione o contrazione di un cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partire da ONTAP Select 9.15.1 è possibile aumentare le dimensioni di un cluster esistente da sei a otto nodi e ridurre le dimensioni del cluster da otto a sei nodi. Non sono supportati altri scenari di espansione o contrazione del cluster.

La procedura viene avviata da ONTAP Select Deploy utilizzando l'interfaccia CLI, API o Web.



== Considerazioni su hardware e storage

Le funzionalità di espansione e contrazione del cluster sono limitate nei seguenti modi:

* Il supporto è limitato ai cluster creati sugli host hypervisor ESX. Le seguenti versioni di ESX sono compatibili con ONTAP Select 9.15.1 e versioni successive:
+
** ESXi 8,0 U3
** ESXi 8,0 U2
** ESXi 8,0 U1
** ESXi 8,0GA
** ESXi 7,0 U3
** ESXi 7,0




Le seguenti espansioni e contrazioni del cluster non sono attualmente supportate:

* Espansioni da cluster a uno, due o quattro nodi a cluster a sei o otto nodi.
* Contrazioni da cluster a sei o otto nodi a cluster a uno, due o quattro nodi.




== Espandere il cluster

Con la funzionalità di espansione del cluster è possibile aumentare le dimensioni di un cluster esistente da sei a otto nodi.

.A proposito di questa attività
In preparazione alla procedura di espansione del cluster, vengono aggiunti all'inventario nuovi host ESX e vengono assegnati i dettagli dei nuovi nodi. Prima di avviare il processo di espansione del cluster, un controllo preliminare della rete verifica la rete interna selezionata.

.Prima di iniziare
* Quando si implementa un cluster multi-nodo, è necessario conoscere link:https://docs.netapp.com/us-en/ontap-select/task_adm_connectivity.html["controllo della connettività di rete"].
* Verificare di disporre dei dettagli di licenza per i nuovi nodi.


.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina e selezionare *Espandi cluster*.
. Passare alla sezione *ha Pair 4*.
. Scegli i dettagli di configurazione della coppia ha (high Availability) per la quarta coppia ha, tra cui:
+
** Tipo di istanza
** Nomi dei nodi
** Host dell'hypervisor associati
** Indirizzi IP dei nodi
** Licenze
** Configurazione di rete
** Configurazione dello storage (tipo RAID e pool di storage)


. Selezionare *Salva coppia ha* per salvare i dettagli della configurazione.
. Fornire le credenziali ONTAP, quindi selezionare *Espandi cluster*.
. Selezionare *Avanti* ed eseguire il controllo preliminare della rete selezionando *Esegui*.
+
Il controllo preliminare della rete convalida che la rete interna selezionata per il traffico del cluster ONTAP funziona correttamente.

. Selezionare *Espandi cluster* per avviare il processo di espansione del cluster, quindi selezionare *OK* nella finestra di dialogo.
+
L'espansione del cluster può richiedere fino a 45 minuti.

. Monitorare il processo di espansione del cluster multi-step per confermare che il cluster si sia espanso correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.


.Al termine
Dopo aver espanso il cluster, è necessario eseguire il backup dei dati di configurazione di ONTAP Select Deploy.



== Contrarre il cluster

È possibile diminuire le dimensioni di un cluster esistente da un cluster a otto nodi a un cluster a sei nodi con la funzionalità di contrazione del cluster.

.A proposito di questa attività
La coppia ha desiderata di nodi nel cluster viene selezionata per prepararsi alla contrazione del cluster durante la procedura.

.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina, quindi selezionare *Contract Cluster*.
. Seleziona i dettagli di configurazione della coppia ha per qualsiasi coppia ha che desideri rimuovere e fornisci le credenziali ONTAP, quindi seleziona *cluster contratto*.
+
Il contratto del cluster può richiedere fino a 30 minuti.

. Monitorare il processo di contrazione del cluster multi-step per confermare che il cluster si è contrattato correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.

