---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: Quando si utilizzano le licenze per i Tier di capacità, è necessario acquisire un file di licenza per ogni nodo ONTAP Select. Il file di licenza definisce la capacità di storage per il nodo e viene bloccato nel nodo tramite il numero di serie univoco a nove cifre assegnato da NetApp. 
---
= Acquisire una licenza per il livello di capacità ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si utilizzano le licenze per i Tier di capacità, è necessario acquisire un file di licenza per ogni nodo ONTAP Select. Il file di licenza definisce la capacità di storage per il nodo e viene bloccato nel nodo tramite il numero di serie univoco a nove cifre assegnato da NetApp.

.Prima di iniziare
* È necessario disporre del numero di serie della licenza a nove cifre assegnato al nodo ONTAP Select da NetApp.
* Dovresti attendere almeno 24 ore dalla data di spedizione dell'ordine di acquisto prima di acquisire un file di licenza.
* Hai esaminato il link:sizing-capacity-tier-license.html["considerazioni per il dimensionamento di una licenza Capacity Tiers"].


.A proposito di questa attività
È necessario eseguire questa attività per ogni nodo ONTAP Select che richiede una licenza Capacity Tiers.

.Fasi
. link:https://register.netapp.com/register/getlicensefile["Accedi al sito delle licenze ONTAP Select"^].
. Accedi utilizzando le credenziali del tuo account NetApp.
. Nella pagina *License Generator*, selezionare l'offerta di licenza desiderata dal menu a discesa.
. Compila i campi rimanenti nella pagina *License Generator*, incluso il *Product Serial #*.
+
Il "numero di serie del prodotto" è il numero di serie del nodo ONTAP Select.

. Seleziona *Invia*.
. Una volta convalidata la richiesta, selezionare il metodo di consegna della licenza.
+
È possibile selezionare *Scarica licenza* o *Invia licenza*.

. Confermare di aver ricevuto il file di licenza in base al metodo di consegna selezionato.


.Al termine
È necessario caricare il file di licenza nell'utility di amministrazione di deploy prima di poterlo applicare a un nodo ONTAP Select.
