---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partire da ONTAP Select 9.15.1 è possibile aumentare le dimensioni di un cluster esistente da sei a otto nodi e ridurre le dimensioni del cluster da otto a sei nodi. 
---
= Espansione o contrazione di un cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aumentare la dimensione del cluster di un cluster ONTAP Select esistente da un cluster a sei nodi a un cluster a otto nodi e ridurne la dimensione da un cluster a otto nodi a un cluster a sei nodi

Le seguenti espansioni e contrazioni dei cluster non sono supportate:

* Espansioni da cluster a uno, due o quattro nodi a cluster a sei o otto nodi.
* Contrazioni da cluster a sei o otto nodi a cluster a uno, due o quattro nodi.


[NOTE]
====
Per modificare il numero di nodi in un cluster in una dimensione non supportata dall'espansione o dalla contrazione del cluster, è necessario eseguire le seguenti attività:

. Distribuisci un nuovo cluster multi-nodo utilizzando link:task_cli_deploy_cluster.html["CLI"] o il link:task_deploy_cluster.html["interfaccia utente web"] fornito con l'utilità di amministrazione ONTAP Select Deploy.
. Se applicabile, migrare i dati al nuovo cluster utilizzando link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replica SnapMirror"^] .


====
È possibile avviare le procedure di espansione e contrazione del cluster da ONTAP Select Deploy tramite CLI, API o interfaccia Web.



== Considerazioni su hardware e storage

La funzionalità di espansione e contrazione del cluster è supportata sugli host hypervisor KVM ed ESXi.

[role="tabbed-block"]
====
.KVM
--
A partire da ONTAP Select 9.17.1, l'espansione e la contrazione dei cluster sono supportate sugli host hypervisor KVM.

L'espansione e la contrazione del cluster sono supportate dalle seguenti versioni dell'hypervisor KVM:

* Red Hat Enterprise Linux a 64 bit 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6
* Rocky Linux 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6


--
.ESXi
--
A partire da ONTAP Select 9.15.1, l'espansione e la contrazione dei cluster sono supportate sugli host hypervisor ESXi.

L'espansione e la contrazione dei cluster sono supportate dalle seguenti versioni dell'hypervisor ESXi:

* ESXi 8,0 U3
* ESXi 8,0 U2
* ESXi 8,0 U1
* ESXi 8,0GA
* ESXi 7,0 U3
* ESXi 7,0


--
====


== Espandere il cluster

Utilizzare la funzionalità di espansione del cluster per aumentare le dimensioni di un cluster esistente da sei a otto nodi.

.A proposito di questa attività
In preparazione all'espansione del cluster, nuovi host ESXi e KVM vengono aggiunti all'inventario e vengono assegnati i dettagli dei nuovi nodi. Prima di avviare il processo di espansione del cluster, un pre-controllo di rete verifica la rete interna selezionata.

.Prima di iniziare
* Quando si distribuisce un cluster multi-nodo, è necessario avere familiarità con il controllo della connettività di rete. È possibile eseguire il controllo della connettività di rete utilizzando link:task_adm_connectivity.html["interfaccia utente web"] o il link:task_cli_connectivity.html["CLI"] .
* Verificare di disporre dei dettagli di licenza per i nuovi nodi.


.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina e selezionare *Espandi cluster*.
. Passare alla sezione *ha Pair 4*.
. Selezionare i seguenti dettagli di configurazione della coppia ad alta disponibilità (HA) per la quarta coppia HA:
+
** Tipo di istanza
** Nomi dei nodi
** Host dell'hypervisor associati
** Indirizzi IP dei nodi
** Licenze
** Configurazione di rete
** Configurazione dello storage (tipo RAID e pool di storage)


. Selezionare *Salva coppia ha* per salvare i dettagli della configurazione.
. Fornire le credenziali ONTAP e selezionare *Espandi cluster*.
. Selezionare *Avanti* ed eseguire il controllo preliminare della rete selezionando *Esegui*.
+
Il controllo preliminare della rete convalida che la rete interna selezionata per il traffico del cluster ONTAP funziona correttamente.

. Selezionare *Espandi cluster* per avviare il processo di espansione del cluster, quindi selezionare *OK* nella finestra di dialogo.
+
L'espansione del cluster può richiedere fino a 45 minuti.

. Monitorare il processo di espansione del cluster multi-step per confermare che il cluster si sia espanso correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.


.Al termine
Dopo aver espanso il cluster, è necessario eseguire il backup dei dati di configurazione di ONTAP Select Deploy.



== Contrarre il cluster

Utilizzare la funzionalità di contrazione del cluster per ridurre le dimensioni di un cluster esistente da otto a sei nodi.

.A proposito di questa attività
La coppia ha desiderata di nodi nel cluster viene selezionata per prepararsi alla contrazione del cluster durante la procedura.

.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina, quindi selezionare *Contract Cluster*.
. Seleziona i dettagli di configurazione della coppia ha per qualsiasi coppia ha che desideri rimuovere e fornisci le credenziali ONTAP, quindi seleziona *cluster contratto*.
+
Il contratto del cluster può richiedere fino a 30 minuti.

. Monitorare il processo di contrazione del cluster multi-step per confermare che il cluster si è contrattato correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.

