---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'È possibile aggiungere un"immagine ONTAP Select all"istanza dell"utilità di amministrazione della distribuzione. Una volta installata l"immagine, è possibile utilizzarla per l"implementazione di un cluster ONTAP Select.' 
---
= Aggiungere un'immagine ONTAP Select da distribuire
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiungere un'immagine ONTAP Select all'istanza dell'utilità di amministrazione della distribuzione. Una volta installata l'immagine, è possibile utilizzarla per l'implementazione di un cluster ONTAP Select.

.Prima di iniziare
Prima di aggiungere nuove immagini ONTAP Select da implementare, è necessario rimuovere tutte le immagini non necessarie.


NOTE: Aggiungere un'immagine ONTAP Select con una versione precedente alla versione originale inclusa nell'istanza dell'utilità di distribuzione. L'aggiunta di versioni più recenti di ONTAP Select non è una configurazione supportata.



== Passaggio 1: scarica l'immagine di installazione

Per iniziare il processo di aggiunta di un'immagine ONTAP Select a un'istanza dell'utilità di implementazione, è necessario scaricare l'immagine di installazione dal sito del supporto NetApp. L'immagine di installazione di ONTAP Select viene formattata come singolo file compresso.

.Fasi
. Accedi al sito di supporto NetApp tramite un browser Web e seleziona *Collegamenti rapidi al supporto*.
. Seleziona *Scarica software* in *Attività principali* e accedi al sito.
. Seleziona *Trova il tuo prodotto*.
. Scorri verso il basso e clicca su * ONTAP Select*.
. In *Altro software disponibile* seleziona *Distribuisci aggiornamento, Aggiornamento nodo, Installazione immagine*.
. Selezionare la versione desiderata del pacchetto di aggiornamento.
. Leggere il Contratto di licenza con l'utente finale (EULA) e selezionare *Accetta e continua*.
. Selezionare e scaricare il pacchetto appropriato, rispondendo a tutti i prompt necessari per il proprio ambiente.




== Passaggio 2: carica l'immagine di installazione su Deploy

Dopo aver acquisito l'immagine di installazione di ONTAP Select, è necessario caricare il file sulla macchina virtuale di implementazione.

.Prima di iniziare
Il file dell'immagine di installazione deve essere disponibile sulla workstation locale. È inoltre necessario disporre della password per l'account utente dell'amministratore di implementazione.

.A proposito di questa attività
Questa attività descrive un metodo per caricare il file sulla macchina virtuale di implementazione. Potrebbero essere disponibili altre opzioni più adatte al proprio ambiente.

.Fase
. In una shell dei comandi sulla workstation locale, carica il file immagine sulla macchina virtuale Deploy, come mostrato negli esempi seguenti:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Risultato
Il file di installazione del nodo viene memorizzato nella home directory dell'utente amministratore.



== Passaggio 3: aggiungere l'immagine di installazione

Aggiungere l'immagine di installazione ONTAP Select alla directory Deploy images in modo che sia disponibile quando si distribuisce un nuovo cluster.

.Prima di iniziare
È necessario conoscere la directory in cui è stato inserito il file dell'immagine di installazione nella macchina virtuale dell'utility di implementazione. Si presuppone che il file si trovi nella home directory dell'amministratore.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore (admin).
. Avvia la shell Bash:
+
[source, cli]
----
shell bash
----
. Inserire il file immagine di installazione nella directory images, come mostrato nell'esempio seguente:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Passaggio 4: visualizzare le immagini di installazione disponibili

Visualizza le immagini ONTAP Select disponibili durante la distribuzione di un nuovo cluster.

.Fasi
. Accedere alla pagina Web della documentazione online dalla macchina virtuale dell'utility di implementazione e accedere utilizzando l'account Administrator (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilizzare il nome di dominio o l'indirizzo IP della macchina virtuale di implementazione.

. Vai in fondo alla pagina e seleziona *Distribuisci*, quindi seleziona *OTTIENI /immagini*.
. Selezionare *Provalo!* per visualizzare le immagini ONTAP Select disponibili.
. Verificare che l'immagine desiderata sia disponibile.

