---
sidebar: sidebar 
permalink: task_vpi_access.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, access, accessing 
summary: È possibile accedere al plug-in Deploy vCenter tramite il client Web vSphere. 
---
= Accedi al plug-in vCenter tramite vSphere
:allow-uri-read: 


[role="lead"]
È possibile accedere al plug-in Deploy vCenter tramite il client Web vSphere.

.Prima di iniziare
È necessario installare il plug-in vCenter. Inoltre, l'account vCenter utilizzato per l'accesso a vSphere deve disporre dei seguenti privilegi:

* NetApp
+
** Implementazione di ONTAP Select
+
*** Amministratore






.Fasi
. Disconnettersi dal client Web vSphere se si è effettuato l'accesso.
. Accedere a vCenter utilizzando il client Web vSphere, selezionare HTML5 e accettare il certificato SSL.
+
La disconnessione e la successiva riconnessa aggiornano le informazioni di configurazione di vCenter.

. Fare clic su *Global Inventory Lists*.


.Risultato
Le opzioni *ONTAP Select Clusters* e *ONTAP Select Deploy* sono disponibili nel riquadro a sinistra. Se non vengono visualizzati, disconnettersi e accedere nuovamente.
