---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: A partire da ONTAP Select 9.15.1, è possibile aumentare o diminuire le dimensioni di un cluster esistente. 
---
= Espandi o contrai un cluster ONTAP Select su host ESXi o KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aumentare o ridurre le dimensioni del cluster di un cluster ONTAP Select esistente per gli host hypervisor ESXi e KVM.  Per entrambi i tipi di host, è possibile aumentare e diminuire la dimensione del cluster con incrementi compresi tra quattro e dodici nodi.

Le seguenti espansioni e contrazioni del cluster non sono supportate per gli host ESXi e KVM:

* Espansioni da cluster a uno o due nodi a cluster a sei, otto, dieci o dodici nodi.
* Contrazioni da cluster a sei, otto, dieci o dodici nodi a cluster a uno o due nodi.


[NOTE]
====
Per modificare il numero di nodi in un cluster in una dimensione non supportata dall'espansione o dalla contrazione del cluster, è necessario eseguire le seguenti attività:

. Distribuisci un nuovo cluster multi-nodo utilizzando link:task_cli_deploy_cluster.html["CLI"] o il link:task_deploy_cluster.html["interfaccia utente web"] fornito con l'utilità di amministrazione ONTAP Select Deploy.
. Se applicabile, migrare i dati al nuovo cluster utilizzando link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replica SnapMirror"^] .


====
È possibile avviare le procedure di espansione e contrazione del cluster da ONTAP Select Deploy tramite CLI, API o interfaccia Web.



== Considerazioni su hardware e storage

La funzionalità di espansione e contrazione del cluster è supportata sui seguenti host hypervisor KVM ed ESXi.

[role="tabbed-block"]
====
.ESXi
--
A partire da ONTAP Select 9.15.1, l'espansione e la contrazione dei cluster sono supportate sugli host hypervisor ESXi.

L'espansione e la contrazione dei cluster sono supportate dalle seguenti versioni dell'hypervisor ESXi:

* ESXi 9.0
* ESXi 8,0 U3
* ESXi 8,0 U2
* ESXi 8,0 U1
* ESXi 8,0GA


--
.KVM
--
A partire da ONTAP Select 9.17.1, l'espansione e la contrazione dei cluster sono supportate sugli host hypervisor KVM.

L'espansione e la contrazione del cluster sono supportate dalle seguenti versioni dell'hypervisor KVM:

* Red Hat Enterprise Linux (RHEL) a 64 bit 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6
* Rocky Linux 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6


[NOTE]
====
Esistono limitazioni del flusso di lavoro RAID software per gli hypervisor KVM sugli host RHEL 10.0 e Rocky Linux 10.0. Per ulteriori informazioni, consultare i seguenti articoli della Knowledge Base:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: messaggio di avviso durante la creazione del Cluster HWR utilizzando RHEL 10 e ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: pool di archiviazione e dischi di archiviazione non visibili per SWR nella pagina di creazione del cluster su host con RHEL10/Rocky 10"^]


====
--
====


== Espandere il cluster

Utilizzare la funzionalità di espansione del cluster per aumentare le dimensioni di un cluster ONTAP Select esistente.

È possibile aumentare le dimensioni di un cluster esistente su un host ESXi o KVM nei seguenti incrementi:

* Da quattro nodi a sei, otto, dieci o dodici nodi
* Da sei nodi a otto, dieci o dodici nodi
* Da otto nodi a dieci o dodici nodi
* Da dieci a dodici nodi


.A proposito di questa attività
In preparazione all'espansione del cluster, nuovi host ESXi e KVM vengono aggiunti all'inventario e vengono assegnati i dettagli dei nuovi nodi. Prima di avviare il processo di espansione del cluster, un pre-controllo di rete verifica la rete interna selezionata.

.Prima di iniziare
* Quando si distribuisce un cluster multi-nodo, è necessario avere familiarità con il controllo della connettività di rete. È possibile eseguire il controllo della connettività di rete utilizzando link:task_adm_connectivity.html["interfaccia utente web"] o il link:task_cli_connectivity.html["CLI"] .
* Verificare di disporre dei dettagli di licenza per i nuovi nodi.


.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina e selezionare *Espandi cluster*.
. Passare alla sezione *ha Pair 4*.
. Selezionare i seguenti dettagli di configurazione della coppia ad alta disponibilità (HA) per la quarta coppia HA:
+
** Tipo di istanza
** Nomi dei nodi
** Host dell'hypervisor associati
** Indirizzi IP dei nodi
** Licenze
** Configurazione di rete
** Configurazione dello storage (tipo RAID e pool di storage)


. Selezionare *Salva coppia ha* per salvare i dettagli della configurazione.
. Fornire le credenziali ONTAP e selezionare *Espandi cluster*.
. Selezionare *Avanti* ed eseguire il controllo preliminare della rete selezionando *Esegui*.
+
Il controllo preliminare della rete convalida che la rete interna selezionata per il traffico del cluster ONTAP funziona correttamente.

. Selezionare *Espandi cluster* per avviare il processo di espansione del cluster, quindi selezionare *OK* nella finestra di dialogo.
+
L'espansione del cluster può richiedere fino a 45 minuti.

. Monitorare il processo di espansione del cluster multi-step per confermare che il cluster si sia espanso correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.


.Al termine
Dopo aver espanso il cluster, dovrestilink:task_cli_clusters.html["eseguire il backup dei dati di configurazione ONTAP Select Deploy"] .



== Contrarre il cluster

Utilizzare la funzionalità di contrazione del cluster per ridurre le dimensioni di un cluster ONTAP Select esistente.

È possibile ridurre le dimensioni di un cluster esistente su un host ESXi o KVM nei seguenti incrementi:

* Da dodici nodi a dieci, otto, sei o quattro nodi
* Da dieci nodi a otto, sei o quattro nodi
* Da otto a sei o quattro nodi
* Da sei a quattro nodi


.A proposito di questa attività
La coppia ha desiderata di nodi nel cluster viene selezionata per prepararsi alla contrazione del cluster durante la procedura.

.Fasi
. Accedere all'interfaccia utente Web dell'utilità di implementazione utilizzando l'account amministratore.
. Selezionare la scheda *Cluster* nella parte superiore della pagina e selezionare il cluster desiderato dall'elenco.
. Nella pagina dei dettagli del quadro strumenti, selezionare l'icona dell'ingranaggio a destra della pagina, quindi selezionare *Contract Cluster*.
. Seleziona i dettagli di configurazione della coppia ha per qualsiasi coppia ha che desideri rimuovere e fornisci le credenziali ONTAP, quindi seleziona *cluster contratto*.
+
Il contratto del cluster può richiedere fino a 30 minuti.

. Monitorare il processo di contrazione del cluster multi-step per confermare che il cluster si è contrattato correttamente.
. Fare riferimento alla scheda *Eventi* per aggiornamenti periodici sullo stato di avanzamento dell'operazione. La pagina viene aggiornata automaticamente a intervalli regolari.

